CREATE OR ALTER PROCEDURE SP_EGRESO_TORO(
  FECHA DATE,
  ANIMAL INTEGER,
  OBSERVACION VARCHAR(255) CHARACTER SET NONE,
  ESTABLECIMIENTO INTEGER,
  RESPONSABLE INTEGER,
  LOG_USUARIO INTEGER,
  LOG_FECHA_MODIFICADO DATE,
  SERVICIO INTEGER,
  ID_GRUPO INTEGER,
  POTRERO INTEGER,
  DISPARADOR INTEGER,
  TIPOEGRESO INTEGER)
AS
DECLARE VARIABLE TIPOEVE INTEGER;
DECLARE VARIABLE IDNUEVOEVENTO INTEGER;
DECLARE VARIABLE COMENTARIO VARCHAR(50);
DECLARE VARIABLE CANTIDADEVENTOSPOSTERIORES INTEGER;
DECLARE VARIABLE BAJA INTEGER;
DECLARE VARIABLE AUX INTEGER;
BEGIN
     /*select fecha_ini from tab_servicios where id_servicio = :servicio into :fecha_ini_servicio*/

    BAJA = NULL;
    SELECT ID_EVENTO
    FROM EVE_EVENTOS
    WHERE ESTABLECIMIENTO = :ESTABLECIMIENTO AND ANIMAL = :ANIMAL AND TIPO = 3/* and fecha between :fecha and :fecha_ini_servicio*/
    INTO : BAJA;
    IF (BAJA IS NULL) THEN
    BEGIN
         TIPOEVE = 16;
         SELECT ID_EVENTO
         FROM SP_CREACION_EVE_EVENTOS(:FECHA,:ANIMAL, :DISPARADOR,:OBSERVACION,:TIPOEVE,:ESTABLECIMIENTO,:RESPONSABLE,
                                      :LOG_USUARIO,:LOG_FECHA_MODIFICADO)
         INTO :IDNUEVOEVENTO;

         /*crea egreso del toro*/
         insert into EVE_EGRESO_TORO
         (SERVICIO,ID_EVENTO)
         values
         (:SERVICIO,:IDNUEVOEVENTO);

         /*cambio la ubicación del Toro*/
         if (TIPOEGRESO = 1) then  /*ESTO ES POR SI CUANDO SE CIERRA UN SERVICIO Y ESTABA SACANDO HEMBRAS NO ME CAMBIE DE UBICACION EL TORO*/
         begin
              COMENTARIO = 'Evento CU disparado por Egreso de Toro';
              select * FROM SP_CAMBIO_UBICACION(:POTRERO, NULL, NULL, :FECHA, :ANIMAL, :COMENTARIO,
             :ESTABLECIMIENTO, :RESPONSABLE, :LOG_USUARIO, :LOG_FECHA_MODIFICADO, :IDNUEVOEVENTO) into aux;
         end
         /*genera le relación N-N*/
         UPDATE REL_PERTENECE_GRUPO SET ACTIVO = 'N'
         WHERE (ANIMAL = :ANIMAL) AND (GRUPO = :ID_GRUPO) AND (ESTABLECIMIENTO = :ESTABLECIMIENTO);

         /* cambio estado reproductivo */
         SELECT CANTIDAD FROM GEN_CAMBIO_ESTADO_REPRODUCTIVO(:ANIMAL, :FECHA)
         INTO :CANTIDADEVENTOSPOSTERIORES;
         
         if (cantidadEventosPosteriores = 0) then
            UPDATE TAB_ANIMALES SET ESTADO_REPRODUCTIVO = 0, ESTADO_ACTUAL = 'Activo/a' WHERE (ID_ANIMAL = :ANIMAL);
         SUSPEND;
   END
END