CREATE OR ALTER PROCEDURE SP_INGRESO_TORO(
  FECHA DATE,
  ANIMAL INTEGER,
  OBSERVACION VARCHAR(255) CHARACTER SET NONE,
  ESTABLECIMIENTO INTEGER,
  RESPONSABLE INTEGER,
  LOG_USUARIO INTEGER,
  LOG_FECHA_MODIFICADO DATE,
  SERVICIO INTEGER,
  ID_GRUPO INTEGER,
  ID_POTRERO INTEGER)
AS
DECLARE VARIABLE FECHA_FIN DATE;
DECLARE VARIABLE TIPOEVE INTEGER;
DECLARE VARIABLE IDNUEVOEVENTO INTEGER;
DECLARE VARIABLE AUXANIMAL INTEGER;
DECLARE VARIABLE COMENTARIO VARCHAR(50);
DECLARE VARIABLE TIPO_SERVICIO INTEGER;
DECLARE VARIABLE CANTIDADEVENTOSPOSTERIORES INTEGER;
DECLARE VARIABLE AUX INTEGER;
BEGIN
    -- recupero que tipo de servicio
    select tipo, FECHA_FIN_ESTIMADA from tab_servicios where (id_servicio = :servicio)
    into :tipo_servicio, :FECHA_FIN;

    IF (FECHA BETWEEN FECHA_FIN AND FECHA_FIN+30) THEN
       UPDATE TAB_SERVICIOS SET FECHA_FIN = :FECHA, FECHA_FIN_ESTIMADA = :FECHA WHERE ID_SERVICIO = :SERVICIO;


    TIPOEVE = 21;
    SELECT ID_EVENTO FROM SP_CREACION_EVE_EVENTOS(:FECHA,:ANIMAL, null,:OBSERVACION,:TIPOEVE,:ESTABLECIMIENTO,:RESPONSABLE,
    :LOG_USUARIO,:LOG_FECHA_MODIFICADO)
    INTO :IDNUEVOEVENTO;
  /*crea ingreso Toro*/

   insert into EVE_INGRESO_TORO
   (ID_EVENTO,SERVICIO)
   values
  (:IDNUEVOEVENTO,:SERVICIO);

   /*EVENTO CAMBIO DE UBICACION*/
   COMENTARIO = 'Evento CU disparado por Ingreso Toro';
   select * FROM SP_CAMBIO_UBICACION (:ID_POTRERO, NULL, NULL, :FECHA, :ANIMAL, :COMENTARIO,
                                          :ESTABLECIMIENTO, :RESPONSABLE, :LOG_USUARIO, :LOG_FECHA_MODIFICADO, :IDNUEVOEVENTO) into aux;



   /*cambio el estado reprod. del Toro*/
   select cantidad from gen_cambio_estado_reproductivo(:animal, :fecha)
   into :cantidadEventosPosteriores;
   if (cantidadEventosPosteriores = 0) then
     begin
       if (tipo_servicio = 1) then  -- servicio natural
         UPDATE TAB_ANIMALES SET ESTADO_REPRODUCTIVO = 3, ESTADO_ACTUAL = 'En Servicio' WHERE (ID_ANIMAL = :ANIMAL); -- en servicio
       else                         -- servicio corral
         UPDATE TAB_ANIMALES SET ESTADO_REPRODUCTIVO = 0, ESTADO_ACTUAL = 'Acticvo/a' WHERE (ID_ANIMAL = :ANIMAL); -- no definido
     end


   select ANIMAL from REL_PERTENECE_GRUPO where (ANIMAL = :ANIMAL)and(GRUPO = :ID_GRUPO)AND(ESTABLECIMIENTO = :ESTABLECIMIENTO )
          into :AUXANIMAL;

   if (AUXANIMAL is not null)then
   begin
       UPDATE REL_PERTENECE_GRUPO
        SET GRUPO = :ID_GRUPO,
           ACTIVO = 'S'
       WHERE(GRUPO = :ID_GRUPO) AND (ESTABLECIMIENTO = :ESTABLECIMIENTO ) AND (ANIMAL = :ANIMAL);
   end
   else
      /*genera le relación N-N*/
     insert into REL_PERTENECE_GRUPO (GRUPO, ANIMAL, ESTABLECIMIENTO, ACTIVO)
       values   (:ID_GRUPO, :ANIMAL, :ESTABLECIMIENTO, 'S');

   SUSPEND;
END