CREATE OR ALTER PROCEDURE SP_ACT_EVENTOS_POSTERIORES(
  FECHA DATE,
  ANIMAL INTEGER,
  ESTABLECIMIENTO INTEGER)
AS
declare variable POTRERO INTEGER;
declare variable RODEO INTEGER;
declare variable CRONOLOGIA_DENTARIA INTEGER;
declare variable ESTADO_REPRODUCTIVO INTEGER;
declare variable CATEGORIA INTEGER;
declare variable COND_CORP INTEGER;
declare variable GDR INTEGER;
declare variable FECHA_AUX DATE;
declare variable EVENTO INTEGER;
BEGIN

     FOR SELECT ID_EVENTO, FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ANIMAL AND ESTABLECIMIENTO = :ESTABLECIMIENTO
         AND FECHA > :FECHA ORDER BY FECHA ASC INTO :EVENTO, :FECHA_AUX
     DO
     BEGIN
          IF (EVENTO IS NOT NULL) THEN
          BEGIN
               POTRERO = NULL;
               RODEO = NULL;
               CRONOLOGIA_DENTARIA = NULL;
               ESTADO_REPRODUCTIVO = NULL;
               CATEGORIA = NULL;
               COND_CORP = NULL;
               GDR = NULL;

               SELECT FIRST 1 * FROM GET_DATOS_ANIMAL_FECHA(:ANIMAL,:ESTABLECIMIENTO,:FECHA_AUX)
               INTO :POTRERO, :RODEO, :CRONOLOGIA_DENTARIA, :ESTADO_REPRODUCTIVO, :CATEGORIA, :COND_CORP, :GDR;

               UPDATE EVE_EVENTOS SET POTRERO = :POTRERO, RODEO = :RODEO, CRONOLOGIA_DENTARIA = :CRONOLOGIA_DENTARIA,
               ESTADO_REPRODUCTIVO = :ESTADO_REPRODUCTIVO, CATEGORIA = :CATEGORIA, CONDICION_CORPORAL = :COND_CORP,
               GDR = :GDR WHERE ID_EVENTO = :EVENTO;
               
               --SUSPEND;
          END
     END

    -- SUSPEND;
END