SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_CALCULAR_PADRES(
  RAZA INTEGER,
  ANIMAL INTEGER,
  ACTUAL DATE)
RETURNS(
  ID_BUSQUEDA INTEGER,
  DESDE DATE,
  HASTA DATE)
AS
DECLARE VARIABLE DIAS_GESTACION INTEGER;
DECLARE VARIABLE DIAS_VENTANA INTEGER;
DECLARE VARIABLE RANGO_INFERIOR DATE;
DECLARE VARIABLE RANGO_SUPERIOR DATE;
DECLARE VARIABLE AUX_SERVICIO INTEGER;
DECLARE VARIABLE AUX_GRUPO INTEGER;
DECLARE VARIABLE AUX_TIPO VARCHAR(2);
DECLARE VARIABLE PADRE_INTERNO INTEGER;
DECLARE VARIABLE PADRE_EXTERNO INTEGER;
DECLARE VARIABLE ID_AUX INTEGER;
DECLARE VARIABLE AUX_DATE DATE;
DECLARE VARIABLE EXISTE INTEGER;
DECLARE VARIABLE AUX_RP VARCHAR(10);
DECLARE VARIABLE EMBRION INTEGER;
DECLARE VARIABLE P1 INTEGER;
DECLARE VARIABLE EXT1 VARCHAR(1);
DECLARE VARIABLE P2 INTEGER;
DECLARE VARIABLE EXT2 VARCHAR(1);
DECLARE VARIABLE M INTEGER;
DECLARE VARIABLE MINT VARCHAR(1);
DECLARE VARIABLE INTERNO VARCHAR(1);
DECLARE VARIABLE ESTABLECIMIENTO INTEGER;
DECLARE VARIABLE ESTAB_ACTUAL INTEGER;
DECLARE VARIABLE AUX_HBA VARCHAR(10);
DECLARE VARIABLE AUX_NOMBRE VARCHAR(100);
BEGIN
  /* RECUPERO UN ID_AUX PARA INSERTAR LOS PADRES LUEGO ESTE IDENTIFICADOR ES EL QUE DEVUELVO Y LO LLAMO PADRE EN EL SP CALCULAR RAZA*/
  ID_AUX = GEN_ID(GEN_ID_AUXANIMALEXTERNO,1);

  /* RECUPERO LOS DIAS DE GESTACION DE LA RAZA DE LA MADRE */
  SELECT CR.DIAS_GESTACION, TA.ESTABLECIMIENTO FROM COD_RAZAS CR, TAB_ANIMALES TA WHERE (TA.ID_ANIMAL = :ANIMAL) /*AND (TA.ESTABLECIMIENTO = :ESTABLECIMIENTO)*/ AND (TA.RAZA = CR.ID_RAZA)
  INTO :DIAS_GESTACION, :ESTAB_ACTUAL;

  /* RECUPERO EL VALOR DEL PARAMETRO DE DIAS DE GRACIA HACIA ATRAS Y ADELANTE */
  SELECT RPE.VALOR FROM SYS_JUEGO_PARAMETROS SJP, REL_PARAMETROS_ESTABLECIMIENTO RPE WHERE (SJP.ID_PARAMETRO = RPE.PARAMETRO) AND (RPE.ESTABLECIMIENTO = :ESTAB_ACTUAL) AND (SJP.NOMBRE = 'BEVENGES')
  INTO :DIAS_VENTANA;

  /* CALCULO LOS LIMITES DEL RANGO */
  RANGO_INFERIOR = ( ACTUAL - DIAS_GESTACION ) - DIAS_VENTANA;
  RANGO_SUPERIOR = ( ACTUAL - DIAS_GESTACION ) + DIAS_VENTANA;

  DESDE = RANGO_INFERIOR;
  HASTA = RANGO_SUPERIOR;

  /* BUSCO LOS SERVICIOS QUE ENTRAN DENTRO DEL RANGO RECIEN CALCULADO EN EL CUAL ESTUVO EL ANIMAL */
  FOR SELECT TS.ID_SERVICIO, TS.GRUPO, CTS.CODIGO, TS.ESTABLECIMIENTO
      FROM TAB_SERVICIOS TS, COD_TIPOS_SERVICIO CTS
      WHERE /*(TS.ESTABLECIMIENTO = :ESTABLECIMIENTO)
      AND */((:RANGO_INFERIOR BETWEEN FECHA_INICIO AND FECHA_FIN)
          OR (FECHA_INICIO BETWEEN :RANGO_INFERIOR AND :RANGO_SUPERIOR))
      AND (TS.TIPO = CTS.ID_TIPO_SERVICIO)
      AND (:ANIMAL IN (SELECT RPG.ANIMAL
                       FROM REL_PERTENECE_GRUPO RPG
                       WHERE (RPG.GRUPO = TS.GRUPO) AND (RPG.ESTABLECIMIENTO = TS.ESTABLECIMIENTO)))
      INTO :AUX_SERVICIO, :AUX_GRUPO, :AUX_TIPO, :ESTABLECIMIENTO
  DO
    BEGIN
      IF (AUX_TIPO = 'IA') THEN /* INSEMINACION ARTIFICIAL */
        BEGIN
          SELECT FIRST 1 TS.ANIMAL, TS.ANIMAL_EXTERNO
          FROM EVE_INSEMINACION_ARTIFICIAL EIA, EVE_EVENTOS EE, TAB_SEMEN TS
          WHERE (EE.ID_EVENTO = EIA.ID_EVENTO) AND (EIA.SERVICIO = :AUX_SERVICIO)
          AND (EE.ANIMAL = :ANIMAL) AND (EE.ESTABLECIMIENTO = :ESTABLECIMIENTO) AND (TS.ID_SEMEN = EIA.SEMEN)
          INTO :PADRE_INTERNO, :PADRE_EXTERNO;
          IF (PADRE_INTERNO > 0) THEN
            BEGIN   /* EL SEMEN ES INTERNO */
              SELECT ID_RP, ID_HBA, NOMBRE FROM TAB_ANIMALES
              WHERE ((ID_ANIMAL = :PADRE_INTERNO) AND (ESTABLECIMIENTO = :ESTABLECIMIENTO))
              INTO :AUX_RP, :AUX_HBA, :AUX_NOMBRE;
              INSERT INTO AUX_ANIMALES_EXTERNOS (ID_AUX, ID_ANIMAL_EXTERNO, ID_RP, ID_HBA, NOMBRE, INTERNO, SEXO) VALUES (:ID_AUX, :PADRE_INTERNO, :AUX_RP, :AUX_HBA, :AUX_NOMBRE,'S',1);
            END
          ELSE /* EL SEMEN ES EXTERNO */
            IF (PADRE_EXTERNO > 0) THEN
            BEGIN
              SELECT DISTINCT ID_RP, ID_HBA, NOMBRE FROM TAB_ANIMALES_EXTERNOS WHERE ((ID_ANIMAL_EXTERNO = :PADRE_EXTERNO))
              INTO :AUX_RP, :AUX_HBA, :AUX_NOMBRE;
              INSERT INTO AUX_ANIMALES_EXTERNOS (ID_AUX, ID_ANIMAL_EXTERNO, ID_RP, ID_HBA, NOMBRE, INTERNO, SEXO) VALUES (:ID_AUX, :PADRE_EXTERNO, :AUX_RP, :AUX_HBA, :AUX_NOMBRE ,'N',1);
            END
        END
      ELSE
        IF (AUX_TIPO = 'CO') THEN /* SERVICIO A CORRAL */
          BEGIN
            SELECT FIRST 1 EE.ANIMAL FROM EVE_EVENTOS EE, EVE_INGRESO_TORO EIT WHERE (EE.ID_EVENTO = EIT.ID_EVENTO) AND (EE.ESTABLECIMIENTO = :ESTABLECIMIENTO) AND (EIT.SERVICIO = :AUX_SERVICIO)
            INTO :PADRE_INTERNO;
            SELECT ID_RP, ID_HBA, NOMBRE FROM TAB_ANIMALES
            WHERE ((ID_ANIMAL = :PADRE_INTERNO) AND (ESTABLECIMIENTO = :ESTABLECIMIENTO))
            INTO :AUX_RP, :AUX_HBA, :AUX_NOMBRE;
            INSERT INTO AUX_ANIMALES_EXTERNOS (ID_AUX, ID_ANIMAL_EXTERNO, ID_RP, ID_HBA, NOMBRE, INTERNO, SEXO) VALUES (:ID_AUX, :PADRE_INTERNO, :AUX_RP, :AUX_HBA, :AUX_NOMBRE,'S',1);
          END
        ELSE
          IF (AUX_TIPO = 'CA') THEN  /* SERVICIO NATURAL */
            BEGIN  /* CALCULO LAS FECHAS DE INGRESO DE TORO O EGRESO DE TORO */
              FOR SELECT EE.FECHA, EE.ANIMAL FROM EVE_INGRESO_TORO EIT, EVE_EVENTOS EE WHERE ((EIT.ID_EVENTO = EE.ID_EVENTO) AND (EIT.SERVICIO = :AUX_SERVICIO))
              INTO :AUX_DATE, :PADRE_INTERNO
              DO
                BEGIN
                  EXISTE = 0;
                  IF (AUX_DATE <= RANGO_SUPERIOR ) THEN /* SI TENGO UN INGRESO DE TORO ANNTES DEL FIN DE LA VENTANA LO TENGO EN CUENTA */
                    IF ((AUX_DATE > RANGO_INFERIOR) AND (AUX_DATE <= RANGO_SUPERIOR))THEN  /* SI EL INGRESO DE TORO ESTA EN LA VENTANA */
                      BEGIN
                        SELECT COUNT(*) FROM AUX_ANIMALES_EXTERNOS WHERE (ID_AUX = :ID_AUX) AND (ID_ANIMAL_EXTERNO = :PADRE_INTERNO) AND (INTERNO = 'S')
                        INTO :EXISTE;
                        IF (EXISTE = 0) THEN
                          BEGIN
                            SELECT ID_RP, ID_HBA, NOMBRE FROM TAB_ANIMALES
                            WHERE ((ID_ANIMAL = :PADRE_INTERNO) AND (ESTABLECIMIENTO = :ESTABLECIMIENTO))
                            INTO :AUX_RP, :AUX_HBA, :AUX_NOMBRE;
                            INSERT INTO AUX_ANIMALES_EXTERNOS (ID_AUX, ID_ANIMAL_EXTERNO, ID_RP, ID_HBA, NOMBRE, INTERNO, SEXO) VALUES (:ID_AUX, :PADRE_INTERNO, :AUX_RP, :AUX_HBA, :AUX_NOMBRE,'S',1);
                          END
                      END
                    ELSE      /* SI EL INGRESO ESTA ANTES DE LA VENTANA, ME FIJO SI EL EGRESO ESTA EN LA VENTANA */
                      BEGIN
                        SELECT FIRST 1 EE.FECHA FROM EVE_EGRESO_TORO EET, EVE_EVENTOS EE WHERE ((EET.ID_EVENTO = EE.ID_EVENTO) AND (EET.SERVICIO = :AUX_SERVICIO) AND (EE.ANIMAL = :PADRE_INTERNO))
                        INTO :AUX_DATE;
                        IF (AUX_DATE > RANGO_INFERIOR) THEN
                          BEGIN
                            SELECT COUNT(*) FROM AUX_ANIMALES_EXTERNOS WHERE (ID_AUX = :ID_AUX) AND (ID_ANIMAL_EXTERNO = :PADRE_INTERNO) AND (INTERNO = 'S')
                            INTO :EXISTE;
                            IF (EXISTE = 0) THEN
                              BEGIN
                                SELECT ID_RP, ID_HBA, NOMBRE FROM TAB_ANIMALES
                                WHERE ((ID_ANIMAL = :PADRE_INTERNO) AND (ESTABLECIMIENTO = :ESTABLECIMIENTO))
                                INTO :AUX_RP, :AUX_HBA, :AUX_NOMBRE;
                                INSERT INTO AUX_ANIMALES_EXTERNOS (ID_AUX, ID_ANIMAL_EXTERNO, ID_RP, ID_HBA, NOMBRE, INTERNO, SEXO) VALUES (:ID_AUX, :PADRE_INTERNO, :AUX_RP, :AUX_HBA, :AUX_NOMBRE,'S',1);
                              END
                          END
                      END
                END
            END
  END
  -- SE BUSCAN LOS PADRES Y LAS MADRES A PARTIR DE LA TRANSFERENCIA EMBRIONARIA
  FOR SELECT EMBRION, ESTABLECIMIENTO
      FROM EVE_TRANSFERENCIA ET JOIN EVE_EVENTOS EE ON ET.ID_EVENTO = EE.ID_EVENTO
      WHERE EE.FECHA BETWEEN :DESDE AND :HASTA AND EE.ANIMAL = :ANIMAL /*AND EE.ESTABLECIMIENTO = :ESTABLECIMIENTO*/
      INTO :EMBRION, :ESTABLECIMIENTO
  DO
  BEGIN
       SELECT PADRE_1, PADRE_EXTERNO_1, PADRE_2, PADRE_EXTERNO_2, MADRE, MADRE_INTERNA FROM TAB_EMBRIONES
       WHERE ID_EMBRION = :EMBRION INTO :P1, :EXT1, :P2, :EXT2, :M, :MINT;

       IF (MINT = 'S') THEN
          SELECT ID_RP, ID_HBA, NOMBRE FROM TAB_ANIMALES WHERE ID_ANIMAL = :M INTO :AUX_RP, :AUX_HBA, :AUX_NOMBRE;
       ELSE
           SELECT ID_RP, ID_HBA, NOMBRE FROM TAB_ANIMALES_EXTERNOS WHERE ID_ANIMAL_EXTERNO = :M INTO :AUX_RP, :AUX_HBA, :AUX_NOMBRE;

       EXISTE = 0;
       SELECT COUNT(*) FROM AUX_ANIMALES_EXTERNOS WHERE ID_AUX = :ID_AUX AND ID_ANIMAL_EXTERNO = :M
       AND INTERNO = :MINT INTO :EXISTE;
       IF (EXISTE = 0) THEN
          INSERT INTO AUX_ANIMALES_EXTERNOS (ID_AUX, ID_ANIMAL_EXTERNO, ID_RP, ID_HBA, NOMBRE, INTERNO, SEXO) VALUES (:ID_AUX, :M, :AUX_RP, :AUX_HBA, :AUX_NOMBRE, :MINT, 2);

       IF (EXT1 = 'S') THEN
       BEGIN
            INTERNO = 'N';
            SELECT ID_RP, ID_HBA, NOMBRE FROM TAB_ANIMALES_EXTERNOS WHERE ID_ANIMAL_EXTERNO = :P1 INTO :AUX_RP, :AUX_HBA, :AUX_NOMBRE;
       END
       ELSE
       BEGIN
            SELECT ID_RP, ID_HBA, NOMBRE FROM TAB_ANIMALES WHERE ID_ANIMAL = :P1 INTO :AUX_RP, :AUX_HBA, :AUX_NOMBRE;
            INTERNO = 'S';
       END

       EXISTE = 0;
       SELECT COUNT(*) FROM AUX_ANIMALES_EXTERNOS WHERE ID_AUX = :ID_AUX AND ID_ANIMAL_EXTERNO = :P1
       AND INTERNO = :EXT1 INTO :EXISTE;
       IF (EXISTE = 0) THEN
          INSERT INTO AUX_ANIMALES_EXTERNOS (ID_AUX, ID_ANIMAL_EXTERNO, ID_RP, ID_HBA, NOMBRE, INTERNO, SEXO) VALUES (:ID_AUX, :P1, :AUX_RP, :AUX_HBA, :AUX_NOMBRE, :INTERNO, 1);


       IF (P2 > 0) THEN
       BEGIN
            IF (EXT2 = 'S') THEN
            BEGIN
                 SELECT ID_RP, ID_HBA, NOMBRE FROM TAB_ANIMALES_EXTERNOS WHERE ID_ANIMAL_EXTERNO = :P2 INTO :AUX_RP, :AUX_HBA, :AUX_NOMBRE;
                 INTERNO = 'N';
            END
            ELSE
            BEGIN
                 INTERNO = 'S';
                 SELECT ID_RP, ID_HBA, NOMBRE FROM TAB_ANIMALES WHERE ID_ANIMAL = :P2 INTO :AUX_RP, :AUX_HBA, :AUX_NOMBRE;
            END

            EXISTE = 0;
            SELECT COUNT(*) FROM AUX_ANIMALES_EXTERNOS WHERE ID_AUX = :ID_AUX AND ID_ANIMAL_EXTERNO = :P2
            AND INTERNO = :EXT2 INTO :EXISTE;
            IF (EXISTE = 0) THEN
               INSERT INTO AUX_ANIMALES_EXTERNOS (ID_AUX, ID_ANIMAL_EXTERNO, ID_RP, ID_HBA, NOMBRE, INTERNO, SEXO) VALUES (:ID_AUX, :P2, :AUX_RP, :AUX_HBA, :AUX_NOMBRE, :INTERNO, 1);
       END

  END

  ID_BUSQUEDA = ID_AUX;
  SUSPEND;  
END ^ 

SET TERM ; ^

