SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_SERVICIO_NATURAL(
  NOMBRE VARCHAR(50) CHARACTER SET NONE,
  FECHA_INICIO DATE,
  FECHA_FIN_ESTIMADA DATE,
  ACTIVO VARCHAR(1) CHARACTER SET NONE,
  ESTABLECIMIENTO INTEGER,
  TIPO INTEGER,
  POTRERO INTEGER)
RETURNS(
  ID_SERVICIO INTEGER,
  ID_GRUPO INTEGER)
AS
DECLARE VARIABLE NOMBREGRUPO VARCHAR(50);
Begin
   /*crea el grupo automático*/
   ID_GRUPO = Gen_Id(GEN_ID_GRUPOS,0);
   NOMBREGRUPO = :NOMBRE ;
 --  insert into TAB_GRUPOS
 --  (ID_GRUPO, ESTABLECIMIENTO, NOMBRE, DESCRIPCION, TIPO)
 --  values
 --  (:ID_GRUPO, :ESTABLECIMIENTO, :NOMBREGRUPO, ' Grupo Auto', 'S');
   /*crea es servicio*/
   ID_SERVICIO = Gen_Id(GEN_ID_TABSERVICIO,1);
   insert into TAB_SERVICIOS
   (ID_SERVICIO, NOMBRE, FECHA_INICIO, FECHA_FIN, FECHA_FIN_ESTIMADA, ACTIVO, TIPO, GRUPO, ESTABLECIMIENTO, POTRERO)
   values
   (:ID_SERVICIO, :NOMBRE, :FECHA_INICIO, :FECHA_FIN_ESTIMADA, :FECHA_FIN_ESTIMADA, :ACTIVO, :TIPO, :ID_GRUPO, :ESTABLECIMIENTO, :POTRERO);
   suspend;
END ^ 

SET TERM ; ^

