SET TERM ^ ;

CREATE OR ALTER PROCEDURE REP_EXTRAER_INFO_LOTES(
  ESTABLECIMIENTO INTEGER)
RETURNS(
  HECTAREAS INTEGER,
  RECURSO_FORRAJERO VARCHAR(50) CHARACTER SET NONE,
  FECHA_RECURSO DATE,
  CANT_NOVILLOS INTEGER,
  CANT_TERNEROS INTEGER,
  CANT_TERNERAS INTEGER,
  CANT_TOROS INTEGER,
  CANT_VACAS INTEGER,
  CANT_VAQUILLONAS INTEGER,
  TOTAL INTEGER,
  NOMBRE VARCHAR(50) CHARACTER SET NONE,
  CAB_NOVILLOS DECIMAL(18, 3),
  CAB_TERNEROS DECIMAL(18, 3),
  CAB_TERNERAS DECIMAL(18, 3),
  CAB_TOROS DECIMAL(18, 3),
  CAB_VACAS DECIMAL(18, 3),
  CAB_VAQUILLONAS DECIMAL(18, 3),
  EQ_NOVILLOS DECIMAL(18, 3),
  EQ_TERNEROS DECIMAL(18, 3),
  EQ_TERNERAS DECIMAL(18, 3),
  EQ_TOROS DECIMAL(18, 3),
  EQ_VACAS DECIMAL(18, 3),
  EQ_VAQUILLONAS DECIMAL(18, 3),
  TOTAL_CABEZAS DECIMAL(18, 3),
  TOTAL_EQ DECIMAL(18, 3))
AS
DECLARE VARIABLE ID INTEGER;
BEGIN
  id = 0;
  hectareas = 0;
  
  FOR SELECT ID_ANIMAL_EXTERNO, RAZA, NOMBRE FROM aux_animales_externos
      INTO :id, :HECTAREAS, :NOMBRE
  DO
    BEGIN
         SELECT * FROM rep_categorias_potrero(:id,:ESTABLECIMIENTO)
         INTO :CANT_TOROS,:CANT_VACAS,:CANT_TERNEROS,:CANT_NOVILLOS,
              :CANT_TERNERAS,:CANT_VAQUILLONAS,:RECURSO_FORRAJERO,:FECHA_RECURSO,
              :TOTAL;
         IF (HECTAREAS > 0) THEN
         BEGIN
              CAB_NOVILLOS = :CANT_NOVILLOS / (:HECTAREAS+0.00001);
              CAB_TERNEROS = :CANT_TERNEROS / (:HECTAREAS+0.00001);
              CAB_TERNERAS = :CANT_TERNERAS / (:HECTAREAS+0.00001);
              CAB_TOROS = :CANT_TOROS / (:HECTAREAS+0.00001);
              CAB_VACAS = :CANT_VACAS / (:HECTAREAS+0.00001);
              CAB_VAQUILLONAS = :CANT_VAQUILLONAS / (:HECTAREAS+0.00001);
              TOTAL_CABEZAS = CAB_NOVILLOS+CAB_TERNERAS+CAB_TERNEROS+CAB_TOROS+CAB_VACAS+CAB_VAQUILLONAS;
         END
         SUSPEND;
END
END ^ 

SET TERM ; ^ 

