SET TERM ^ ;

CREATE OR ALTER PROCEDURE GET_EXISTENCIA_POR_POTRERO(
  POTRERO INTEGER,
  DESDE DATE,
  HASTA DATE)
RETURNS(
  TOTALEXISTENCIA DECIMAL(18, 1),
  PROMEDIOEXISTENCIA DECIMAL(18, 2))
AS
DECLARE VARIABLE NOMRESPONSABLEAUX VARCHAR(100) CHARACTER SET NONE;
DECLARE VARIABLE TOTALPARCIALALTAS INTEGER;
DECLARE VARIABLE TOTALPARCIALCAMBUBSALIDA INTEGER;
DECLARE VARIABLE TOTALPARCIALBAJAS INTEGER;
DECLARE VARIABLE TOTALPARCIALALTASAUX INTEGER;
DECLARE VARIABLE TOTALPARCIALBAJASAUX INTEGER;
DECLARE VARIABLE DIASENTREFECHAS INTEGER;
DECLARE VARIABLE FECHAAUX DATE;
DECLARE VARIABLE TOTALPARCIALCAMBUBSALIDAAUX INTEGER;
DECLARE VARIABLE TOTALPARCIALEXISTENCIA INTEGER;
BEGIN
     TOTALEXISTENCIA = 0;
     PROMEDIOEXISTENCIA = 0;
     FECHAAUX = :DESDE -1;
     DIASENTREFECHAS = (:HASTA - :DESDE) + 1;

     /*/*/
     TOTALPARCIALALTAS = 0;
     TOTALPARCIALCAMBUBSALIDA = 0;
     TOTALPARCIALBAJAS = 0;

     TOTALPARCIALALTASAUX = 0;
     TOTALPARCIALCAMBUBSALIDAAUX = 0;
     TOTALPARCIALBAJASAUX = 0;
     TOTALPARCIALEXISTENCIA=0;

     --select count(*) from eve_eventos ee join eve_alta_directa ead on (ee.id_evento = ead.id_evento) where ee.tipo = 2 and ee.potrero = :potrero and ee.fecha <= :desde INTO :TOTALPARCIALALTAS;

     --select count(*) from eve_eventos ee join eve_nacimiento en on (ee.id_evento = en.id_evento) where ee.tipo = 23 and ee.potrero = :potrero and ee.fecha <= :desde INTO :TOTALPARCIALNACIMIENTOS;

     select count(*) from eve_eventos ee join eve_baja eb on (ee.id_evento = eb.id_evento) where ee.tipo = 3 and ee.potrero = :potrero and ee.fecha < :desde INTO :TOTALPARCIALBAJAS;

     select count(*) from EVE_EVENTOS ee join EVE_CAMBIO_UBICACION eb on(ee.ID_EVENTO = eb.ID_EVENTO) where ee.tipo = 5 and /*eb.ESTABLECIMIENTO_ANTERIOR is null and*/ eb.POTRERO = :potrero and ee.fecha < :desde into :TOTALPARCIALALTAS;

     select count(*) from EVE_EVENTOS ee join EVE_CAMBIO_UBICACION eb on(ee.ID_EVENTO = eb.ID_EVENTO) where ee.tipo = 5 and /*eb.ESTABLECIMIENTO_ANTERIOR is null and*/ ee.POTRERO = :potrero and ee.POTRERO <> eb.POTRERO and ee.fecha < :desde into :TOTALPARCIALCAMBUBSALIDA;

     TOTALEXISTENCIA = :TOTALEXISTENCIA + :TOTALPARCIALALTAS - :TOTALPARCIALCAMBUBSALIDA - :TOTALPARCIALBAJAS;
     TOTALPARCIALEXISTENCIA = TOTALEXISTENCIA;
     TOTALEXISTENCIA = 0;
     TOTALPARCIALALTAS = 0;
     TOTALPARCIALCAMBUBSALIDA = 0;
     TOTALPARCIALBAJAS = 0;
     FECHAAUX = :FECHAAUX + 1;
     WHILE (:FECHAAUX <= :HASTA) DO
           BEGIN


                TOTALPARCIALALTAS = 0;
                TOTALPARCIALCAMBUBSALIDA = 0;
                TOTALPARCIALBAJAS = 0;
                TOTALPARCIALALTASAUX = 0;
                TOTALPARCIALCAMBUBSALIDAAUX = 0;
                TOTALPARCIALBAJASAUX = 0;


                select count(*) from eve_eventos ee join eve_baja eb on (ee.id_evento = eb.id_evento) where ee.tipo = 3 and ee.potrero = :potrero and ee.fecha = :FECHAAUX INTO :TOTALPARCIALBAJASAUX;

                select count(*) from EVE_EVENTOS ee join EVE_CAMBIO_UBICACION eb on(ee.ID_EVENTO = eb.ID_EVENTO) where ee.tipo = 5 and eb.ESTABLECIMIENTO_ANTERIOR is null and eb.POTRERO = :potrero and ee.fecha = :FECHAAUX into :TOTALPARCIALALTASAUX;

                select count(*) from EVE_EVENTOS ee join EVE_CAMBIO_UBICACION eb on(ee.ID_EVENTO = eb.ID_EVENTO) where ee.tipo = 5 and eb.ESTABLECIMIENTO_ANTERIOR is null and ee.POTRERO = :potrero and ee.POTRERO <> eb.POTRERO and ee.fecha = :FECHAAUX into :TOTALPARCIALCAMBUBSALIDAAUX;


                TOTALPARCIALALTAS = :TOTALPARCIALALTAS + :TOTALPARCIALALTASAUX;
                TOTALPARCIALCAMBUBSALIDA = :TOTALPARCIALCAMBUBSALIDA + :TOTALPARCIALCAMBUBSALIDAAUX;
                TOTALPARCIALBAJAS = :TOTALPARCIALBAJAS + :TOTALPARCIALBAJASAUX;

                TOTALPARCIALEXISTENCIA = TOTALPARCIALEXISTENCIA + :TOTALPARCIALALTAS - :TOTALPARCIALCAMBUBSALIDA - :TOTALPARCIALBAJAS;
                TOTALEXISTENCIA = :TOTALEXISTENCIA + TOTALPARCIALEXISTENCIA;
                FECHAAUX = :FECHAAUX + 1;
           END
     if (:DIASENTREFECHAS <> 0) then
        PROMEDIOEXISTENCIA = :TOTALEXISTENCIA / :DIASENTREFECHAS;
     SUSPEND;
END ^ 

SET TERM ; ^ 

