SET TERM ^ ; 

CREATE OR ALTER PROCEDURE SP_ALTA_ANIMALES_ERA
AS
DECLARE VARIABLE ESTA INTEGER;
DECLARE VARIABLE ANIMAL INTEGER;
DECLARE VARIABLE RP VARCHAR(10);
DECLARE VARIABLE HBA VARCHAR(10);
DECLARE VARIABLE SEXO INTEGER;
DECLARE VARIABLE CATEG INTEGER;
DECLARE VARIABLE RAZA INTEGER;
DECLARE VARIABLE TIPO VARCHAR(50);
DECLARE VARIABLE NACIMIENTO DATE;
BEGIN
     FOR SELECT ESTABLECIMIENTO, ID_ANIMAL, ID_RP, ID_HBA, FECHA_NACIMIENTO, SEXO, CATEGORIA, RAZA, V1
         FROM AUX_ANIMALES
         INTO :ESTA, :ANIMAL, :RP, :HBA, :NACIMIENTO, :SEXO, :CATEG, :RAZA, :TIPO
     DO
     BEGIN
          IF (TIPO = 'Actualizar') THEN
          BEGIN
               UPDATE TAB_ANIMALES SET ID_RP = :RP, ID_HBA = :HBA, FECHA_NACIMIENTO = :NACIMIENTO, SEXO = :SEXO
               WHERE ID_ANIMAL = :ANIMAL  AND ESTABLECIMIENTO = :ESTA;
          END
          IF (TIPO = 'Dar de Alta') THEN
          BEGIN
               ANIMAL = GEN_ID(GEN_ID_TABANIMAL,1);
               EXECUTE PROCEDURE SP_ALTA_DIRECTA_ANIMAL(:ANIMAL,:RP,NULL,:NACIMIENTO,NULL,NULL,NULL,0,:RAZA,0,:CATEG,
               0,NULL,NULL,NULL,0,NULL,:HBA,NULL,NULL,:RP,NULL,:SEXO,NULL,:NACIMIENTO,3,NULL,NULL,NULL,:ESTA,0,1,CAST('TODAY' AS DATE),
               NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0,'N',NULL);
          END
     END
END ^ 

SET TERM ; ^ 

