SET TERM ^ ;

CREATE OR ALTER PROCEDURE REP_LISTADO_PERSONALIZADO(
  RP_GENEALOGIA INTEGER,
  NOMBRE_GENEALOGIA INTEGER,
  APODO_GENEALOGIA INTEGER,
  CANT INTEGER)
RETURNS(
  ID_RP VARCHAR(10) CHARACTER SET NONE,
  ID_SENASA VARCHAR(10) CHARACTER SET NONE,
  ID_IE VARCHAR(64) CHARACTER SET NONE,
  ID_HBA VARCHAR(10) CHARACTER SET NONE,
  ID_PC VARCHAR(10) CHARACTER SET NONE,
  CATEGORIA VARCHAR(100) CHARACTER SET NONE,
  RAZA VARCHAR(100) CHARACTER SET NONE,
  COLOR VARCHAR(50) CHARACTER SET NONE,
  TIPO_REG VARCHAR(50) CHARACTER SET NONE,
  CRIADOR VARCHAR(100) CHARACTER SET NONE,
  PROPIETARIO VARCHAR(100) CHARACTER SET NONE,
  ORIGEN VARCHAR(100) CHARACTER SET NONE,
  POTRERO VARCHAR(100) CHARACTER SET NONE,
  RODEO VARCHAR(100) CHARACTER SET NONE,
  ESTABLECIMIENTO VARCHAR(100) CHARACTER SET NONE,
  PESO_ACTUAL VARCHAR(7) CHARACTER SET NONE,
  FECHA_ULTIMA_PESADA DATE,
  PESO_NAC VARCHAR(7) CHARACTER SET NONE,
  PESO_205 VARCHAR(7) CHARACTER SET NONE,
  FECHA_DEST DATE,
  PESO_365 VARCHAR(7) CHARACTER SET NONE,
  FECHA_ANIO DATE,
  PESO_505 VARCHAR(7) CHARACTER SET NONE,
  FECHA_18 DATE,
  CE VARCHAR(7) CHARACTER SET NONE,
  ALZADA VARCHAR(7) CHARACTER SET NONE,
  FRAME VARCHAR(7) CHARACTER SET NONE,
  PADRE VARCHAR(100) CHARACTER SET NONE,
  MADRE VARCHAR(100) CHARACTER SET NONE,
  ABUELO_PAT VARCHAR(100) CHARACTER SET NONE,
  ABUELA_PAT VARCHAR(100) CHARACTER SET NONE,
  ABUELO_MAT VARCHAR(100) CHARACTER SET NONE,
  ABUELA_MAT VARCHAR(100) CHARACTER SET NONE,
  FECHA_ULTIMO_SERV DATE,
  TIPO_ULTIMO_SERV VARCHAR(50) CHARACTER SET NONE,
  TORO_ULTIMO_SERV VARCHAR(100) CHARACTER SET NONE,
  FECHA_ANTEULTIMO_SERV DATE,
  TIPO_ANTEULTIMO_SERV VARCHAR(50) CHARACTER SET NONE,
  TORO_ANTEULTIMO_SERV VARCHAR(100) CHARACTER SET NONE,
  FECHA_ULTIMO_TACTO DATE,
  RESULT_ULTIMO_TACTO VARCHAR(100) CHARACTER SET NONE,
  FECHA_ANTEULTIMO_TACTO DATE,
  RESULT_ANTEULTIMO_TACTO VARCHAR(100) CHARACTER SET NONE,
  FECHA_ULTIMO_PARTO DATE,
  TIPO_ULTIMO_PARTO VARCHAR(50) CHARACTER SET NONE,
  FECHA_ANTEULTIMO_PARTO DATE,
  TIPO_ANTEULTIMO_PARTO VARCHAR(50) CHARACTER SET NONE,
  CANT_CRIAS INTEGER,
  FECHA_PROB_PARTO DATE,
  FECHA_ULTIMO_TRAT DATE,
  ULTIMO_TRAT VARCHAR(100) CHARACTER SET NONE,
  FECHA_ANTEULTIMO_TRAT DATE,
  ANTEULTIMO_TRAT VARCHAR(100) CHARACTER SET NONE,
  GDR VARCHAR(100) CHARACTER SET NONE,
  COND_CORP VARCHAR(7) CHARACTER SET NONE,
  NOMBRE VARCHAR(100) CHARACTER SET NONE,
  APODO VARCHAR(100) CHARACTER SET NONE,
  FECHA_NAC DATE,
  SUBCATEGORIZACION VARCHAR(100) CHARACTER SET NONE,
  INFO_AFIP VARCHAR(2) CHARACTER SET NONE,
  CARAVANA_OFICIAL VARCHAR(20) CHARACTER SET NONE)
AS
DECLARE VARIABLE ID_ANIMAL INTEGER;
DECLARE VARIABLE ID_CATEG INTEGER;
DECLARE VARIABLE ID_RAZA INTEGER;
DECLARE VARIABLE ID_ESTAB INTEGER;
DECLARE VARIABLE ID_ORIG INTEGER;
DECLARE VARIABLE ID_SUBCAT INTEGER;
DECLARE VARIABLE ID_COLOR INTEGER;
DECLARE VARIABLE ID_PROP INTEGER;
DECLARE VARIABLE ID_PADRE INTEGER;
DECLARE VARIABLE ID_MADRE INTEGER;
DECLARE VARIABLE ID_ABUELO_PAT INTEGER;
DECLARE VARIABLE ID_ABUELA_PAT INTEGER;
DECLARE VARIABLE ID_ABUELO_MAT INTEGER;
DECLARE VARIABLE ID_ABUELA_MAT INTEGER;
DECLARE VARIABLE ID_POT INTEGER;
DECLARE VARIABLE ID_ROD INTEGER;
DECLARE VARIABLE EVE_DESTE INTEGER;
DECLARE VARIABLE EVE_PESO_AUX INTEGER;
DECLARE VARIABLE EVE_GESTA INTEGER;
DECLARE VARIABLE EVE_GESTA_2 INTEGER;
DECLARE VARIABLE EVE_SERVICIO INTEGER;
DECLARE VARIABLE EVE_SANI INTEGER;
DECLARE VARIABLE EVE_SANI_2 INTEGER;
DECLARE VARIABLE PARTO INTEGER;
DECLARE VARIABLE ID_CRIADOR INTEGER;
DECLARE VARIABLE TIPO_SERV INTEGER;
DECLARE VARIABLE ABORTO INTEGER;
DECLARE VARIABLE HOY DATE;
DECLARE VARIABLE ID_GDR INTEGER;
DECLARE VARIABLE ID_COND INTEGER;
DECLARE VARIABLE MBI INTEGER;
DECLARE VARIABLE MBE INTEGER;
DECLARE VARIABLE PI INTEGER;
DECLARE VARIABLE PE INTEGER;
DECLARE VARIABLE CANT_P INTEGER;
DECLARE VARIABLE RP_AUX VARCHAR(10);
DECLARE VARIABLE APODO_AUX VARCHAR(100);
DECLARE VARIABLE NOM_AUX VARCHAR(100);
DECLARE VARIABLE RELAC VARCHAR(10);
DECLARE VARIABLE AUX_IDENT VARCHAR(100);
DECLARE VARIABLE PARTO_2 INTEGER;
DECLARE VARIABLE ID_AUX_TRAT INTEGER;
DECLARE VARIABLE VAR_CC VARCHAR(25);
DECLARE VARIABLE I INTEGER;
DECLARE VARIABLE EVENTO_DIAGNOSTICO INTEGER;
DECLARE VARIABLE FECHA_DIAGNOSTICO DATE;
DECLARE VARIABLE DIAS_AL_DIAGNOSTICO INTEGER;
DECLARE VARIABLE DIAS_GESTACION_RAZA INTEGER;
DECLARE VARIABLE INFO_AFIP_AUX VARCHAR(1);
BEGIN

IF (CANT > 0) THEN
BEGIN
     I = 0;
     WHILE (I < CANT) DO
     BEGIN
          ID_RP = NULL;
          ID_SENASA = NULL;
          ID_IE = NULL;
          ID_HBA = NULL;
          ID_PC = NULL;
          CATEGORIA = NULL;
          RAZA = NULL;
          COLOR = NULL;
          TIPO_REG = NULL;
          CRIADOR = NULL;
          PROPIETARIO = NULL;
          ORIGEN = NULL;
          POTRERO = NULL;
          RODEO = NULL;
          ESTABLECIMIENTO = NULL;
          PESO_ACTUAL = NULL;
          FECHA_ULTIMA_PESADA = NULL;
          PESO_NAC = NULL;
          PESO_205 = NULL;
          FECHA_DEST = NULL;
          PESO_365 = NULL;
          FECHA_ANIO = NULL;
          PESO_505 = NULL;
          FECHA_18 = NULL;
          CE = NULL;
          ALZADA = NULL;
          FRAME = NULL;
          PADRE = NULL;
          MADRE = NULL;
          ABUELO_PAT = NULL;
          ABUELA_PAT = NULL;
          ABUELO_MAT = NULL;
          ABUELA_MAT = NULL;
          FECHA_ULTIMO_SERV = NULL;
          TIPO_ULTIMO_SERV = NULL;
          TORO_ULTIMO_SERV = NULL;
          FECHA_ANTEULTIMO_SERV = NULL;
          TIPO_ANTEULTIMO_SERV = NULL;
          TORO_ANTEULTIMO_SERV = NULL;
          FECHA_ULTIMO_TACTO = NULL;
          RESULT_ULTIMO_TACTO = NULL;
          FECHA_ANTEULTIMO_TACTO = NULL;
          RESULT_ANTEULTIMO_TACTO = NULL;
          FECHA_ULTIMO_PARTO = NULL;
          TIPO_ULTIMO_PARTO = NULL;
          FECHA_ANTEULTIMO_PARTO = NULL;
          TIPO_ANTEULTIMO_PARTO = NULL;
          CANT_CRIAS = NULL;
          FECHA_PROB_PARTO = NULL;
          FECHA_ULTIMO_TRAT = NULL;
          ULTIMO_TRAT = NULL;
          FECHA_ANTEULTIMO_TRAT = NULL;
          ANTEULTIMO_TRAT = NULL;
          GDR = NULL;
          COND_CORP = NULL;
          NOMBRE = NULL;
          APODO = NULL;
          FECHA_NAC = NULL;
          SUBCATEGORIZACION = NULL;
          INFO_AFIP = NULL;
          CARAVANA_OFICIAL = NULL;
          SUSPEND;

          I = I + 1;
     END
END
ELSE
BEGIN
     HOY = CAST ('TODAY' AS DATE);
     FOR SELECT ID_ANIMAL FROM AUX_ANIMALES
         INTO :ID_ANIMAL
     DO
     BEGIN
          ID_RP = NULL;
          ID_SENASA = NULL;
          ID_IE = NULL;
          ID_HBA = NULL;
          ID_PC = NULL;
          CATEGORIA = NULL;
          RAZA = NULL;
          COLOR = NULL;
          TIPO_REG = NULL;
          CRIADOR = NULL;
          PROPIETARIO = NULL;
          ORIGEN = NULL;
          POTRERO = NULL;
          RODEO = NULL;
          ESTABLECIMIENTO = NULL;
          PESO_ACTUAL = NULL;
          FECHA_ULTIMA_PESADA = NULL;
          PESO_NAC = NULL;
          PESO_205 = NULL;
          FECHA_DEST = NULL;
          PESO_365 = NULL;
          FECHA_ANIO = NULL;
          PESO_505 = NULL;
          FECHA_18 = NULL;
          CE = NULL;
          ALZADA = NULL;
          FRAME = NULL;
          PADRE = NULL;
          MADRE = NULL;
          ABUELO_PAT = NULL;
          ABUELA_PAT = NULL;
          ABUELO_MAT = NULL;
          ABUELA_MAT = NULL;
          FECHA_ULTIMO_SERV = NULL;
          TIPO_ULTIMO_SERV = NULL;
          TORO_ULTIMO_SERV = NULL;
          FECHA_ANTEULTIMO_SERV = NULL;
          TIPO_ANTEULTIMO_SERV = NULL;
          TORO_ANTEULTIMO_SERV = NULL;
          FECHA_ULTIMO_TACTO = NULL;
          RESULT_ULTIMO_TACTO = NULL;
          FECHA_ANTEULTIMO_TACTO = NULL;
          RESULT_ANTEULTIMO_TACTO = NULL;
          FECHA_ULTIMO_PARTO = NULL;
          TIPO_ULTIMO_PARTO = NULL;
          FECHA_ANTEULTIMO_PARTO = NULL;
          TIPO_ANTEULTIMO_PARTO = NULL;
          CANT_CRIAS = NULL;
          FECHA_PROB_PARTO = NULL;
          FECHA_ULTIMO_TRAT = NULL;
          ULTIMO_TRAT = NULL;
          FECHA_ANTEULTIMO_TRAT = NULL;
          ANTEULTIMO_TRAT = NULL;
          GDR = NULL;
          COND_CORP = NULL;

          NOMBRE = NULL;
          APODO = NULL;
          SUBCATEGORIZACION = NULL;
          INFO_AFIP = NULL;
          CARAVANA_OFICIAL = NULL;

          ID_CATEG = NULL;
          ID_RAZA = NULL;
          ID_POT = NULL;
          ID_ROD = NULL;
          ID_ESTAB = NULL;
          ID_ORIG = NULL;
          ID_PROP = NULL;
          ID_CRIADOR = NULL;
          ID_GDR = NULL;
          ID_COND = NULL;
          INFO_AFIP_AUX = NULL;

          MBI = NULL;
          MBE = NULL;
          PI = NULL;
          PE = NULL;

          FECHA_NAC = NULL;

          SELECT ID_RP, ID_SENASA, ID_HBA, ID_PC, ID_IE, CATEGORIA, RAZA, POTRERO, RODEO, ESTABLECIMIENTO,
          ORIGEN_ANIMAL, PROPIETARIO, CRIADOR, CAST(PESO205 AS VARCHAR(7)), CAST(PESO365 AS VARCHAR(7)), CAST(PESO550 AS VARCHAR(7)),
    CAST(ULTIMO_PESO AS VARCHAR(7)), CAST(CIRCUNFERENCIA_ESCROTAL AS VARCHAR(7)),
          ESTADO_LACTACION, GDR, CAST(CONDICION_CORPORAL  AS VARCHAR(7)), SUBCATEGORIA, COLOR, NOMBRE, APODO, FECHA_NACIMIENTO, INFORMADO_AFIP, CARAVANA_OFICIAL
          FROM TAB_ANIMALES WHERE ID_ANIMAL = :ID_ANIMAL
          INTO :ID_RP, :ID_SENASA, :ID_HBA, :ID_PC, :ID_IE, :ID_CATEG, :ID_RAZA, :ID_POT, :ID_ROD, :ID_ESTAB,
          :ID_ORIG, :ID_PROP, :ID_CRIADOR, :PESO_205, :PESO_365, :PESO_505, :PESO_ACTUAL, :CE,
          :CANT_CRIAS, :ID_GDR, :ID_COND, :ID_SUBCAT, :ID_COLOR, :NOMBRE, :APODO, :FECHA_NAC, :INFO_AFIP_AUX, :CARAVANA_OFICIAL;

          IF (CANT_CRIAS < 0) THEN
             CANT_CRIAS = 0;
             
          IF (INFO_AFIP_AUX = 'S')
             THEN INFO_AFIP = 'SI';
             ELSE INFO_AFIP = 'NO';

          SELECT FIRST 1 CSZ.NOMBRE FROM EVE_EVENTOS EE JOIN EVE_ACTIVIDAD EA ON EE.ID_EVENTO = EA.ID_EVENTO
          JOIN COD_SUBCATEGORIZACION CSZ ON EA.SUBCATEGORIZACION = CSZ.ID_SUBCATEGORIZACION
          WHERE EE.ANIMAL = :ID_ANIMAL ORDER BY FECHA DESC INTO :SUBCATEGORIZACION;


          SELECT NOMBRE FROM COD_CATEGORIAS WHERE ID_CATEGORIA = :ID_CATEG INTO :CATEGORIA;

          SELECT NOMBRE, DIAS_GESTACION FROM COD_RAZAS WHERE ID_RAZA = :ID_RAZA INTO :RAZA, :DIAS_GESTACION_RAZA;

          SELECT NOMBRE FROM COD_COLORES WHERE ID_COLOR = :ID_COLOR INTO :COLOR;

          SELECT NOMBRE FROM COD_SUBCATEGORIAS WHERE ID_SUBCATEGORIA = :ID_SUBCAT INTO TIPO_REG;

          SELECT NOMBRE FROM TAB_POTREROS WHERE ID_POTRERO = :ID_POT AND ESTABLECIMIENTO = :ID_ESTAB
          INTO :POTRERO;

          SELECT NOMBRE FROM TAB_RODEOS WHERE ID_RODEO = :ID_ROD AND ESTABLECIMIENTO = :ID_ESTAB
          INTO :RODEO;

          SELECT NOMBRE FROM TAB_ESTABLECIMIENTOS WHERE ID_ESTABLECIMIENTO = :ID_ESTAB INTO :ESTABLECIMIENTO;

          SELECT NOMBRE FROM COD_ORIGEN WHERE ID_ORIGEN = :ID_ORIG INTO :ORIGEN;
          SELECT NOMBRE FROM COD_PROPIETARIO WHERE ID_PROPIETARIO = :ID_PROP INTO :PROPIETARIO;
          SELECT NOMBRE FROM COD_CRIADOR WHERE ID_CRIADOR = :ID_CRIADOR INTO :CRIADOR;

          SELECT NOMBRE FROM COD_GDR WHERE ID_GDR = :ID_GDR INTO :GDR;

          SELECT VALOR FROM REL_PARAMETROS_ESTABLECIMIENTO WHERE ESTABLECIMIENTO = :ID_ESTAB AND PARAMETRO = 3
          INTO :VAR_CC;
          IF (VAR_CC = '10') THEN
             SELECT VALOR_ESCALA_10 FROM COD_CONDICIONES_CORPORALES WHERE ID_CONDICION_CORPORAL = :ID_COND
             INTO :COND_CORP;
          ELSE
              SELECT VALOR_ESCALA_5 FROM COD_CONDICIONES_CORPORALES WHERE ID_CONDICION_CORPORAL = :ID_COND
              INTO :COND_CORP;

          --PESOS
          SELECT FIRST 1 FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND ESTABLECIMIENTO = :ID_ESTAB
          AND TIPO = 25 ORDER BY FECHA DESC INTO :FECHA_ULTIMA_PESADA;

          SELECT FIRST 1 EE.FECHA FROM EVE_EVENTOS EE JOIN EVE_PESO EP ON EE.ID_EVENTO = EP.ID_EVENTO
          WHERE EE.ANIMAL = :ID_ANIMAL AND EE.ESTABLECIMIENTO = :ID_ESTAB AND EE.TIPO = 25 AND EP.DIAS = 'D'
          ORDER BY FECHA DESC INTO :FECHA_DEST;

          SELECT FIRST 1 EE.FECHA FROM EVE_EVENTOS EE JOIN EVE_PESO EP ON EE.ID_EVENTO = EP.ID_EVENTO
          WHERE EE.ANIMAL = :ID_ANIMAL AND EE.ESTABLECIMIENTO = :ID_ESTAB AND EE.TIPO = 25 AND EP.DIAS = 'A'
          ORDER BY FECHA DESC INTO :FECHA_ANIO;

          SELECT FIRST 1 EE.FECHA FROM EVE_EVENTOS EE JOIN EVE_PESO EP ON EE.ID_EVENTO = EP.ID_EVENTO
          WHERE EE.ANIMAL = :ID_ANIMAL AND EE.ESTABLECIMIENTO = :ID_ESTAB AND EE.TIPO = 25 AND EP.DIAS = 'T'
          ORDER BY FECHA DESC INTO :FECHA_18;

          --MEDICION FRAME
          SELECT FIRST 1 EMF.ALTURA, EMF.VALOR FROM EVE_EVENTOS EE JOIN EVE_MEDICION_FRAME EMF
          ON EE.ID_EVENTO = EMF.ID_EVENTO WHERE EE.ANIMAL = :ID_ANIMAL AND EE.ESTABLECIMIENTO = :ID_ESTAB
          AND EE.TIPO = 22 ORDER BY EE.FECHA DESC INTO :ALZADA, :FRAME;

          --GENEALOGIA
          FOR SELECT ID_RP, NOMBRE, APODO, RELACION FROM GET_ARBOL_GENEA_MULTI_PADRES(1,:ID_ANIMAL,0,'','N')
              INTO :RP_AUX, :NOM_AUX, :APODO_AUX, :RELAC
          DO
          BEGIN
               AUX_IDENT = '';
   
               IF (RP_AUX IS NULL) THEN
                  RP_AUX = '';
               IF (NOM_AUX IS NULL) THEN
                  NOM_AUX = '';
               IF (APODO_AUX IS NULL) THEN
                  APODO_AUX = '';
   
      IF (RP_GENEALOGIA = 1) THEN
      BEGIN
           AUX_IDENT = RP_AUX;
      END
    
      IF (NOMBRE_GENEALOGIA = 1) THEN
      BEGIN
           IF (AUX_IDENT <> '') THEN
              AUX_IDENT = AUX_IDENT || '-' || NOM_AUX;
           ELSE
               AUX_IDENT = NOM_AUX;
      END
   
      IF (APODO_GENEALOGIA = 1) THEN
      BEGIN
           IF (AUX_IDENT <> '') THEN
              AUX_IDENT = AUX_IDENT || '-' || APODO_AUX;
           ELSE
               AUX_IDENT = APODO_AUX;
           END

               IF (RELAC = 'P') THEN
                  PADRE = AUX_IDENT;
               IF (RELAC = 'M') THEN
                  MADRE = AUX_IDENT;
               IF (RELAC = 'PP') THEN
                  ABUELO_PAT = AUX_IDENT;
               IF (RELAC = 'PM') THEN
                  ABUELA_PAT = AUX_IDENT;
               IF (RELAC = 'MP') THEN
                  ABUELO_MAT = AUX_IDENT;
               IF (RELAC = 'MM') THEN
                  ABUELA_MAT = AUX_IDENT;
       END
          --TRATAMIENTOS
          EVE_SANI = NULL;
          EVE_SANI_2 = NULL;
          ID_AUX_TRAT = NULL;
          SELECT FIRST 1 ID_EVENTO, FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND ESTABLECIMIENTO = :ID_ESTAB
          AND (TIPO = 27) ORDER BY FECHA DESC INTO :EVE_SANI, :FECHA_ULTIMO_TRAT;
          IF (EVE_SANI IS NOT NULL) THEN
             SELECT CT.NOMBRE FROM EVE_TRATAMIENTO ET JOIN COD_TRATAMIENTO CT ON ET.ID_TRATAMIENTO = CT.ID_TRATAMIENTO
             WHERE ID_EVENTO = :EVE_SANI INTO :ULTIMO_TRAT;
          SELECT FIRST 1 ID_EVENTO, FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND ESTABLECIMIENTO = :ID_ESTAB
          AND (TIPO = 27) AND ID_EVENTO <> :EVE_SANI ORDER BY FECHA DESC INTO :EVE_SANI_2, :FECHA_ANTEULTIMO_TRAT;
          IF (EVE_SANI_2 IS NOT NULL) THEN
             SELECT CT.NOMBRE FROM EVE_TRATAMIENTO ET JOIN COD_TRATAMIENTO CT ON ET.ID_TRATAMIENTO = CT.ID_TRATAMIENTO
             WHERE ID_EVENTO = :EVE_SANI_2 INTO :ANTEULTIMO_TRAT;

        

          --SERVICIOS
          TIPO_SERV = NULL;
          EVE_SERVICIO = NULL;
          SELECT FIRST 1 TIPO, FECHA, ID_EVENTO FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND ESTABLECIMIENTO = :ID_ESTAB
          AND ((TIPO = 28) OR (TIPO = 20)) ORDER BY FECHA DESC INTO :TIPO_SERV, :FECHA_ULTIMO_SERV, :EVE_SERVICIO;
          IF (TIPO_SERV IS NOT NULL) THEN
          BEGIN
              IF (TIPO_SERV = 28) THEN
                 TIPO_ULTIMO_SERV = 'IA';
              ELSE
                  TIPO_ULTIMO_SERV = 'SN';
          END
          SELECT FIRST 1 TIPO, FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND ESTABLECIMIENTO = :ID_ESTAB
          AND ((TIPO = 28) OR (TIPO = 20)) AND ID_EVENTO <> :EVE_SERVICIO ORDER BY FECHA DESC
          INTO :TIPO_SERV, :FECHA_ANTEULTIMO_SERV;
          IF (TIPO_SERV IS NOT NULL) THEN
          BEGIN
               IF (TIPO_SERV = 28) THEN
                  TIPO_ANTEULTIMO_SERV = 'IA';
               ELSE
                   TIPO_ANTEULTIMO_SERV = 'SN';
          END

          --TACTO
          EVE_GESTA = NULL;
          EVE_GESTA_2 = NULL;
          SELECT FIRST 1 ID_EVENTO, FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND ESTABLECIMIENTO = :ID_ESTAB
          AND TIPO = 13 ORDER BY FECHA DESC INTO :EVE_GESTA, :FECHA_ULTIMO_TACTO;
          IF (EVE_GESTA IS NOT NULL) THEN
          BEGIN
               SELECT CER.NOMBRE FROM EVE_DIAGNOSTICO_GESTACION EDG JOIN COD_ESTADOS_REPRODUCTIVOS CER
               ON CER.ID_ESTADO_REPRODUCTIVO = EDG.ESTADO_REPRODUCTIVO WHERE EDG.ID_EVENTO = :EVE_GESTA
               INTO :RESULT_ULTIMO_TACTO;
          END

          SELECT FIRST 1 ID_EVENTO, FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND ESTABLECIMIENTO = :ID_ESTAB
          AND TIPO = 13 AND ID_EVENTO <> :EVE_GESTA ORDER BY FECHA DESC INTO :EVE_GESTA_2, :FECHA_ANTEULTIMO_TACTO;
          IF (EVE_GESTA_2 IS NOT NULL) THEN
          BEGIN
               SELECT CER.NOMBRE FROM EVE_DIAGNOSTICO_GESTACION EDG JOIN COD_ESTADOS_REPRODUCTIVOS CER
               ON CER.ID_ESTADO_REPRODUCTIVO = EDG.ESTADO_REPRODUCTIVO WHERE EDG.ID_EVENTO = :EVE_GESTA_2
               INTO :RESULT_ANTEULTIMO_TACTO;
          END

          --PROYECCION DE PARTO
          EVENTO_DIAGNOSTICO = NULL;
          SELECT FIRST 1 EE.ID_EVENTO, EE.FECHA, EDG.DIAS_GESTACION FROM EVE_EVENTOS EE JOIN EVE_DIAGNOSTICO_GESTACION EDG
          ON (EE.ID_EVENTO = EDG.ID_EVENTO) WHERE (EE.ANIMAL = :ID_ANIMAL) ORDER BY EE.FECHA DESC
          INTO :EVENTO_DIAGNOSTICO, :FECHA_DIAGNOSTICO, :DIAS_AL_DIAGNOSTICO;

          IF (EVENTO_DIAGNOSTICO IS NOT NULL) THEN
             IF (DIAS_AL_DIAGNOSTICO <> 0) THEN
                FECHA_PROB_PARTO = HOY + DIAS_GESTACION_RAZA - (HOY - FECHA_DIAGNOSTICO  + DIAS_AL_DIAGNOSTICO);

          --PARTO
          PARTO = NULL;
          PARTO_2 = NULL;
          SELECT FIRST 1 ID_EVENTO, FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND TIPO = 24
          ORDER BY FECHA DESC
          INTO :PARTO, :FECHA_ULTIMO_PARTO;
          IF (PARTO IS NOT NULL) THEN
             TIPO_ULTIMO_PARTO = 'PARTO NORMAL';

          SELECT FIRST 1 ID_EVENTO, FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND TIPO = 24 AND ID_EVENTO <> :PARTO
          ORDER BY FECHA DESC
          INTO :PARTO_2, :FECHA_ANTEULTIMO_PARTO;
          IF (PARTO_2 IS NOT NULL) THEN
             TIPO_ANTEULTIMO_PARTO = 'PARTO NORMAL';

          --ABORTO
          ABORTO = NULL;
          IF (FECHA_ULTIMO_TACTO IS NULL) THEN
          BEGIN
               ABORTO = NULL;
            SELECT FIRST 1 ID_EVENTO, FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND TIPO = 1
            AND FECHA BETWEEN :FECHA_ULTIMO_TACTO AND :HOY
            INTO :ABORTO, :FECHA_ULTIMO_PARTO;
            IF (ABORTO IS NOT NULL) THEN
                  TIPO_ULTIMO_PARTO = 'ABORTO';
          END
          IF (FECHA_ANTEULTIMO_TACTO IS NULL) THEN
          BEGIN
               ABORTO = NULL;
            SELECT FIRST 1 ID_EVENTO, FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND TIPO = 1
            AND FECHA BETWEEN :FECHA_ANTEULTIMO_TACTO AND :FECHA_ULTIMO_TACTO
            INTO :ABORTO, :FECHA_ANTEULTIMO_PARTO;
            IF (ABORTO IS NOT NULL) THEN
                  TIPO_ANTEULTIMO_PARTO = 'ABORTO';
          END

          SUSPEND;
     END
END
END ^

SET TERM ; ^

