SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_DESTETE(
  FECHA DATE,
  ANIMAL INTEGER,
  OBSERVACION VARCHAR(255) CHARACTER SET NONE,
  ESTABLECIMIENTO INTEGER,
  RESPONSABLE INTEGER,
  LOG_USUARIO INTEGER,
  LOG_FECHA_MODIFICADO DATE,
  PESO DOUBLE PRECISION,
  TIPO INTEGER,
  ID_GRUPO INTEGER,
  DISPARADOR INTEGER,
  POTRERO INTEGER,
  RODEO INTEGER)
AS
DECLARE VARIABLE TIPOEVE INTEGER;
DECLARE VARIABLE IDNUEVOEVENTO INTEGER;
DECLARE VARIABLE A INTEGER;
DECLARE VARIABLE COMENTARIO VARCHAR(255);
DECLARE VARIABLE AUX_R INTEGER;
DECLARE VARIABLE AUX_P INTEGER;
DECLARE VARIABLE AUX INTEGER;
BEGIN

    TIPOEVE = 10;
    SELECT ID_EVENTO FROM SP_CREACION_EVE_EVENTOS(:FECHA,:ANIMAL,:DISPARADOR,:OBSERVACION,:TIPOEVE,:ESTABLECIMIENTO,:RESPONSABLE,
    :LOG_USUARIO,:LOG_FECHA_MODIFICADO)
    INTO :IDNUEVOEVENTO;

   insert into EVE_DESTETE
     (ID_EVENTO,TIPO)
   values
     (:IDNUEVOEVENTO,:TIPO);

   EXECUTE PROCEDURE SP_PESO (:FECHA,:ANIMAL,'Peso al Destete',:ESTABLECIMIENTO,:RESPONSABLE, :LOG_USUARIO, :LOG_FECHA_MODIFICADO,'D', :PESO,:ID_GRUPO,
       :IDNUEVOEVENTO);

   -- Arma la relacion Grupo eventos
   EXECUTE PROCEDURE Gen_Agregar_En_Grupo (:ESTABLECIMIENTO ,:IDNUEVOEVENTO ,:ID_GRUPO );

  --cambio la ubicación del animal
  /*SELECT ID_ANIMAL FROM TAB_ANIMALES WHERE (ID_ANIMAL= :ANIMAL) AND (POTRERO = :POTRERO)
  INTO :A;
  IF(A IS NULL)then
   begin
     COMENTARIO = 'Evento CU disparado por Destete';
     if (potrero is not null)then
          EXECUTE PROCEDURE SP_CAMBIO_UBICACION(:POTRERO, :RODEO,:ID_GRUPO, :FECHA, :ANIMAL, :COMENTARIO,
             :ESTABLECIMIENTO, :RESPONSABLE, :LOG_USUARIO, :LOG_FECHA_MODIFICADO, :IDNUEVOEVENTO);
   END*/
   IF ((RODEO IS NOT NULL) OR (POTRERO IS NOT NULL)) THEN
      SELECT * FROM SP_CAMBIO_UBICACION(:POTRERO,:RODEO,NULL,:FECHA,:ANIMAL,'Evento CU disparado por Destete',
      :ESTABLECIMIENTO,:RESPONSABLE,:LOG_USUARIO,:LOG_FECHA_MODIFICADO,:IDNUEVOEVENTO) INTO AUX;
END ^ 

SET TERM ; ^

