SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_EGRESO_SERVICIO(
  FECHA DATE,
  ANIMAL INTEGER,
  OBSERVACION VARCHAR(255) CHARACTER SET NONE,
  ESTABLECIMIENTO INTEGER,
  RESPONSABLE INTEGER,
  LOG_USUARIO INTEGER,
  LOG_FECHA_MODIFICADO DATE,
  CONDICION_CORPORAL INTEGER,
  SERVICIO INTEGER,
  ID_GRUPO INTEGER,
  POTRERO INTEGER,
  DISPARADOR INTEGER,
  TIPOEGRESO INTEGER)
AS
DECLARE VARIABLE TIPOEVE INTEGER;
DECLARE VARIABLE IDNUEVOEVENTO INTEGER;
DECLARE VARIABLE COMENTARIO VARCHAR(50);
DECLARE VARIABLE VARANIMAL INTEGER;
DECLARE VARIABLE CANTIDADEVENTOSPOSTERIORES INTEGER;
DECLARE VARIABLE ESTADO INTEGER;
DECLARE VARIABLE EVENTO INTEGER;
DECLARE VARIABLE FECHA_SERV DATE;
DECLARE VARIABLE ESTADO_DIAG INTEGER;
DECLARE VARIABLE FECHA_DIAG DATE;
DECLARE VARIABLE FECHA_PARTO DATE;
DECLARE VARIABLE BAJA INTEGER;
DECLARE VARIABLE EST_ACTUAL VARCHAR(50);
DECLARE VARIABLE AUX INTEGER;
BEGIN
     BAJA = NULL;
     SELECT ID_EVENTO
     FROM EVE_EVENTOS WHERE ESTABLECIMIENTO = :ESTABLECIMIENTO AND ANIMAL = :ANIMAL AND TIPO = 3
     INTO : BAJA;
     IF (BAJA IS NULL) THEN
     BEGIN
          /* cambio estado reproductivo */
          Estado = null;
          ESTADO_DIAG = NULL;
          SELECT FIRST 1 EDG.ESTADO_REPRODUCTIVO, EDG.ESTADO_AUX, EDG.ID_EVENTO, EE.FECHA
          FROM EVE_EVENTOS EE JOIN EVE_DIAGNOSTICO_GESTACION EDG ON EE.ID_EVENTO = EDG.ID_EVENTO
          WHERE EE.TIPO = 13 AND/* EDG.ESTADO_AUX = 2 AND*/ EE.ANIMAL=:ANIMAL
          ORDER BY EE.FECHA DESC
          INTO :ESTADO_DIAG, :ESTADO, :EVENTO, :FECHA_DIAG;

          if (ESTADO IS NOT NULL) then
             UPDATE EVE_DIAGNOSTICO_GESTACION EDG
             SET EDG.ESTADO_REPRODUCTIVO = :ESTADO, EDG.ESTADO_AUX = NULL
             WHERE EDG.ID_EVENTO = :EVENTO;
          ELSE
          IF (ESTADO_DIAG IS NOT NULL) THEN
          BEGIN
               SELECT CANTIDAD FROM GEN_CAMBIO_ESTADO_REPRODUCTIVO(:ANIMAL, :FECHA_DIAG)
               INTO :CANTIDADEVENTOSPOSTERIORES;
               IF ((FECHA_DIAG > FECHA) AND (CANTIDADEVENTOSPOSTERIORES = 0)) THEN
                  ESTADO = ESTADO_DIAG;
          END

          if (ESTADO IS NULL) then
             ESTADO = 5;
          if ((ESTADO = 1) and (fecha > fecha_diag)) then
             ESTADO = 5;

          FECHA_PARTO = NULL;
          SELECT FECHA_INICIO FROM TAB_SERVICIOS WHERE ID_SERVICIO = :SERVICIO
          INTO :FECHA_SERV;

          SELECT FIRST 1 EE.FECHA FROM EVE_EVENTOS EE JOIN EVE_PARTO EP ON EP.ID_EVENTO = EE.ID_EVENTO
          WHERE EE.TIPO = 24 AND EE.ANIMAL = :ANIMAL ORDER BY EE.FECHA DESC
          INTO :FECHA_PARTO;

          IF (FECHA_PARTO IS NULL) THEN
             SELECT FIRST 1 EE.FECHA FROM EVE_EVENTOS EE JOIN EVE_PARTO_MASIVO EPM ON EPM.ID_EVENTO = EE.ID_EVENTO
             WHERE EE.TIPO = 39 AND EE.ANIMAL = :ANIMAL ORDER BY EE.FECHA DESC
             INTO :FECHA_PARTO;

          IF (FECHA_PARTO IS NOT NULL) THEN
          BEGIN
               SELECT CANTIDAD
               FROM GEN_CAMBIO_ESTADO_REPRODUCTIVO(:ANIMAL, :FECHA_PARTO)
               INTO :CANTIDADEVENTOSPOSTERIORES;

               IF ((FECHA_PARTO > FECHA_SERV) AND (CANTIDADEVENTOSPOSTERIORES = 0)) THEN
                  ESTADO = 4;
          END

          TIPOEVE = 15;
          SELECT ID_EVENTO
          FROM SP_CREACION_EVE_EVENTOS(:FECHA,:ANIMAL, :DISPARADOR, :OBSERVACION,:TIPOEVE,:ESTABLECIMIENTO,:RESPONSABLE,
                                       :LOG_USUARIO,:LOG_FECHA_MODIFICADO)
          INTO :IDNUEVOEVENTO;

          /*crea ingreso a Servicio*/
          insert into EVE_EGRESO_SERVICIO
          (SERVICIO,ID_EVENTO)
          values
          (:SERVICIO,:IDNUEVOEVENTO);

          /*cambio la condicion corporal de la Hembra*/
          SELECT ID_ANIMAL FROM TAB_ANIMALES WHERE (ID_ANIMAL= :ANIMAL) AND (CONDICION_CORPORAL = :CONDICION_CORPORAL)
          INTO :varAnimal;

          IF((varAnimal IS NULL)and not(CONDICION_CORPORAL is null))then
          BEGIN
               COMENTARIO = 'Evento CC disparado por Egreso Servicio';
               EXECUTE PROCEDURE SP_CONDICION_CORPORAL( :CONDICION_CORPORAL, :FECHA, :ANIMAL,:COMENTARIO,
               :ESTABLECIMIENTO, :RESPONSABLE, :LOG_USUARIO, :LOG_FECHA_MODIFICADO, :IDNUEVOEVENTO, null);
          END

          /*cambio la ubicación de la Hembra*/
          SELECT ID_ANIMAL FROM TAB_ANIMALES WHERE (ID_ANIMAL= :ANIMAL) AND (POTRERO = :POTRERO)
          INTO :varAnimal;

          if (varAnimal IS NULL) then
          begin
               if (TIPOEGRESO = 2) then
               begin
                    COMENTARIO = 'Evento CU disparado por Egreso Servicio';
                    select * FROM SP_CAMBIO_UBICACION(:POTRERO, NULL, NULL, :FECHA, :ANIMAL,:COMENTARIO,
                    :ESTABLECIMIENTO, :RESPONSABLE, :LOG_USUARIO, :LOG_FECHA_MODIFICADO,:IDNUEVOEVENTO) into aux;
               end
          end

          /*genera le relación N-N*/
          UPDATE REL_PERTENECE_GRUPO
          SET ACTIVO = 'N'
          WHERE (ANIMAL = :ANIMAL) AND (GRUPO = :ID_GRUPO) AND (ESTABLECIMIENTO = :ESTABLECIMIENTO);
          
          SELECT CANTIDAD FROM GEN_CAMBIO_ESTADO_REPRODUCTIVO(:ANIMAL, :FECHA)
          INTO :CANTIDADEVENTOSPOSTERIORES;
          SELECT MSG_ESTADO FROM COD_ESTADOS_REPRODUCTIVOS WHERE ID_ESTADO_REPRODUCTIVO = :ESTADO
          INTO :EST_ACTUAL;

          IF ((CANTIDADEVENTOSPOSTERIORES = 0) OR (ESTADO IS NOT NULL)) THEN
             UPDATE TAB_ANIMALES SET ESTADO_REPRODUCTIVO = :ESTADO, ESTADO_ACTUAL = :EST_ACTUAL WHERE (ID_ANIMAL = :ANIMAL);

          UPDATE EVE_EGRESO_SERVICIO SET ESTADO_REPRODUCTIVO = :ESTADO WHERE (id_evento = :IDNUEVOEVENTO);
     
          SUSPEND;
     END
END ^ 

SET TERM ; ^ 

