SET TERM ^ ; 

CREATE OR ALTER PROCEDURE SP_NACIMIENTO(
  FECHA DATE,
  DISPARADOR INTEGER,
  OBSERVACION VARCHAR(255) CHARACTER SET NONE,
  ESTABLECIMIENTO INTEGER,
  RESPONSABLE INTEGER,
  LOG_USUARIO INTEGER,
  LOG_FECHA_MODIFICADO DATE,
  POTRERO INTEGER,
  RODEO INTEGER,
  NUEVO_SEXO INTEGER,
  PADRE INTEGER,
  MADRE INTEGER,
  MADRE_BIOLOGICA INTEGER,
  PESO INTEGER,
  VIVO VARCHAR(1) CHARACTER SET NONE,
  RP VARCHAR(10) CHARACTER SET NONE,
  SEN VARCHAR(9) CHARACTER SET NONE,
  PC VARCHAR(10) CHARACTER SET NONE,
  HBA VARCHAR(10) CHARACTER SET NONE,
  RA VARCHAR(10) CHARACTER SET NONE,
  OTRO VARCHAR(10) CHARACTER SET NONE,
  IE VARCHAR(64) CHARACTER SET NONE,
  COLOR INTEGER,
  NOMBRE VARCHAR(100) CHARACTER SET NONE,
  APODO VARCHAR(100) CHARACTER SET NONE)
AS
DECLARE VARIABLE TIPOEVE INTEGER;
DECLARE VARIABLE ID_EVENTO INTEGER;
DECLARE VARIABLE ANIMAL INTEGER;
DECLARE VARIABLE AUX INTEGER;
BEGIN

  SELECT NUEVO_ANIMAL FROM SP_AGREGAR_ANIMAL (:ESTABLECIMIENTO, :FECHA, :POTRERO, :RODEO, :NUEVO_SEXO, :PADRE, :MADRE,
                                              :MADRE_BIOLOGICA, :VIVO, :COLOR)
  INTO :ANIMAL;

  TIPOEVE = 23; -- NACIMIENTO

  -- REGISTRO EL EVENTO EN EVE_EVENTOS
  SELECT ID_EVENTO FROM SP_CREACION_EVE_EVENTOS(:FECHA, :ANIMAL, :DISPARADOR, :OBSERVACION, :TIPOEVE, :ESTABLECIMIENTO,
  :RESPONSABLE, :LOG_USUARIO, :LOG_FECHA_MODIFICADO)
  INTO :ID_EVENTO;

  -- REGISTRO EL EVENTO EN EVE_NACIMIENTO
  INSERT INTO EVE_NACIMIENTO
    (ID_EVENTO, VIVO)
  VALUES
    (:ID_EVENTO, :VIVO);

  IF (PESO <> 0) THEN -- REGISTRO EL PESO
    EXECUTE PROCEDURE SP_PESO (:FECHA, :ANIMAL, 'EVENTO PESO DISPARADO POR NACIMIENTO', :ESTABLECIMIENTO, :RESPONSABLE, :LOG_USUARIO,
    :LOG_FECHA_MODIFICADO, 'N', :PESO, NULL, :ID_EVENTO);
  ELSE  --SI NO REGISTRO EL PESO AGREGO UNA ALARMA EN LA AGENDA
    IF (VIVO = 'S') THEN
      EXECUTE PROCEDURE ALA_PESAR_NACIDOS(:FECHA, :ESTABLECIMIENTO, :ID_EVENTO, NULL);

  IF (RP IS NOT NULL) THEN -- REGISTRO LA IDENTIFICACION CON IDENTIFICADORES + NOMBRE = RP  + APODO = RP
  BEGIN
    --Si no tiene apodo, por defecto, el apodo es el RP
    IF (APODO IS NULL) THEN APODO = :RP;
    EXECUTE PROCEDURE SP_IDENTIFICACION (:FECHA, :ANIMAL, 'EVENTO IDENTIFICACION DISPARADO POR NACIMIENTO', :ESTABLECIMIENTO, :RESPONSABLE,
    :LOG_USUARIO, :LOG_FECHA_MODIFICADO, NULL, :RP, :SEN, :PC, :HBA, :RA, :OTRO, :NOMBRE, :APODO, :ID_EVENTO,'I', :IE);
  END
  ELSE -- SI NO IDENTIFICO EL ANIMAL DISPARO UNA ALARMA EN LA AGENDA
    IF (VIVO = 'S') THEN
      EXECUTE PROCEDURE ALA_IDENTIFICAR_NACIDOS(:FECHA, :ESTABLECIMIENTO, :ID_EVENTO, NULL);

  -- REGISTRO EVENTO CAMBIO UBICACION
  IF ((POTRERO IS NOT NULL) OR (RODEO IS NOT NULL)) THEN
    select * from  SP_CAMBIO_UBICACION(:POTRERO, :RODEO, NULL, :FECHA, :ANIMAL, 'EVENTO CU DISPARADO POR NACIMIENTO', :ESTABLECIMIENTO,
                      :RESPONSABLE, :LOG_USUARIO, :LOG_FECHA_MODIFICADO, :ID_EVENTO) into aux;

/*  EXECUTE PROCEDURE sp_actividad(:FECHA, :ANIMAL,'EVENTO ACTIVIDAD DISPARADO POR NACIMIENTO DE ANIMAL', :ESTABLECIMIENTO,
          :RESPONSABLE, :LOG_USUARIO, :LOG_FECHA_MODIFICADO, 0, null, :ID_EVENTO, 0, 0, NULL, NULL);
*/
  update tab_animales ta set ta.actividad = 0 where ta.id_animal = :animal and ta.establecimiento = :establecimiento;

  -- REGISTRO LA ALARMA PARA LA PRIMER VACUNACION DE BRUCELOSIS PARA DENTRO DE 8 MESES
  IF (VIVO = 'S') THEN
    EXECUTE PROCEDURE ALA_VACUNACION_BRUCELOSIS(:FECHA, :ESTABLECIMIENTO, :ID_EVENTO, NULL);

  EXECUTE PROCEDURE SP_CAMBIO_CATEGORIA_ANIMALES;
  SUSPEND;
END ^ 

SET TERM ; ^ 

