SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_DECLARACION_AFIP(
  FECHA DATE,
  ANIMAL INTEGER,
  OBSERVACION VARCHAR(255) CHARACTER SET NONE,
  ESTABLECIMIENTO INTEGER,
  RESPONSABLE INTEGER,
  LOG_USUARIO INTEGER,
  LOG_FECHA_MODIFICADO DATE,
  ID_GRUPO INTEGER,
  DISPARADOR INTEGER)
AS
DECLARE VARIABLE TIPOEVE INTEGER;
DECLARE VARIABLE IDNUEVOEVENTO INTEGER;
BEGIN
    TIPOEVE = 58;

    SELECT ID_EVENTO FROM SP_CREACION_EVE_EVENTOS(:FECHA,:ANIMAL, :DISPARADOR, :OBSERVACION,:TIPOEVE,:ESTABLECIMIENTO,:RESPONSABLE,
    :LOG_USUARIO,:LOG_FECHA_MODIFICADO)
    INTO :IDNUEVOEVENTO;

    EXECUTE PROCEDURE Gen_Agregar_En_Grupo(:ESTABLECIMIENTO,:IDNUEVOEVENTO,:ID_GRUPO);
    
    UPDATE TAB_ANIMALES SET INFORMADO_AFIP = 'S' WHERE ID_ANIMAL = :ANIMAL;

    SUSPEND;
END ^

SET TERM ; ^

