SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_CARGA_ANIM_DEPS(
  ESTABLECIMIENTO INTEGER,
  TIPOCARGA VARCHAR(2) CHARACTER SET NONE)
AS
DECLARE VARIABLE ANIMAL INTEGER;
DECLARE VARIABLE RP VARCHAR(10);
DECLARE VARIABLE IDENT VARCHAR(10);
DECLARE VARIABLE HBA VARCHAR(10);
DECLARE VARIABLE OTRO VARCHAR(10);
DECLARE VARIABLE NOMBRE VARCHAR(100);
DECLARE VARIABLE SEXO INTEGER;
DECLARE VARIABLE RAZA INTEGER;
DECLARE VARIABLE NACIMIENTO DATE;
DECLARE VARIABLE COLOR INTEGER;
DECLARE VARIABLE CATEG INTEGER;
DECLARE VARIABLE TIPO VARCHAR(20);
BEGIN

  FOR SELECT ID_RP, ID_HBA, NOMBRE, SEXO, FECHA_NACIMIENTO, RAZA, COLOR, TIPO_ALTA
      FROM AUX_ANIMALES
      INTO :RP, :IDENT, :NOMBRE, :SEXO, :NACIMIENTO, :RAZA, :COLOR, :TIPO
  DO
  BEGIN
          SELECT CATEGORIA FROM SP_CALCULAR_CATEGORIA(:NACIMIENTO,:SEXO)
          INTO :CATEG;

          IF ((:RAZA = 2) OR (:RAZA = 3) OR (:RAZA = 29)) THEN
          BEGIN
              HBA = :IDENT;
              OTRO = NULL;
          END
          ELSE
          BEGIN
              HBA = NULL;
              OTRO = :IDENT;
          END

          IF ((:TIPO = '') OR (:TIPO IS NULL)) THEN
          BEGIN
                  IF (:TIPOCARGA = 'I') THEN
                  BEGIN
                       ANIMAL = GEN_ID(GEN_ID_TABANIMAL,1);

                       EXECUTE PROCEDURE SP_ALTA_DIRECTA_ANIMAL(:ANIMAL,:RP,NULL,:NACIMIENTO,NULL,NULL,NULL,0,:RAZA,0,:CATEG,
                       0,NULL,NULL,NULL,0,:OTRO,:HBA,NULL,NULL,:NOMBRE,NULL,:SEXO,NULL,:NACIMIENTO,3,NULL,NULL,NULL,:ESTABLECIMIENTO,0,1,CAST('TODAY' AS DATE),
                       NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,:COLOR,'N');

                  END

                  IF (:TIPOCARGA = 'E') THEN
                  BEGIN
                       ANIMAL = GEN_ID(GEN_ID_TABANIMALEXTERNO,1);

                       INSERT INTO TAB_ANIMALES_EXTERNOS VALUES(:RP,:ESTABLECIMIENTO,:ANIMAL,NULL,:OTRO,:HBA,NULL,NULL,:NOMBRE,NULL,:RAZA,:SEXO,NULL,0,:NACIMIENTO,NULL,NULL,'S',:COLOR,0,NULL,NULL,NULL,NULL,NULL,NULL);
                  END

                  IF (:ANIMAL IS NOT NULL) THEN
                  BEGIN
                     UPDATE AUX_IMP_ERA SET ID_ANIMAL = :ANIMAL WHERE (RP = :RP);
                     UPDATE AUX_IMP_ERA SET TIPO_SERVICIO = :TIPOCARGA WHERE (RP = :RP);
                  END
              END
          ELSE
          BEGIN
                  IF (:TIPO = 'I') THEN
                  BEGIN
                       ANIMAL = GEN_ID(GEN_ID_TABANIMAL,1);

                       EXECUTE PROCEDURE SP_ALTA_DIRECTA_ANIMAL(:ANIMAL,:RP,NULL,:NACIMIENTO,NULL,NULL,NULL,0,:RAZA,0,:CATEG,
                       0,NULL,NULL,NULL,0,:OTRO,:HBA,NULL,NULL,:NOMBRE,NULL,:SEXO,NULL,:NACIMIENTO,3,NULL,NULL,NULL,:ESTABLECIMIENTO,0,1,CAST('TODAY' AS DATE),
                       NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,:COLOR,'N');
                  END

                  IF (:TIPO = 'E') THEN
                  BEGIN
                       ANIMAL = GEN_ID(GEN_ID_TABANIMALEXTERNO,1);

                       INSERT INTO TAB_ANIMALES_EXTERNOS VALUES(:RP,:ESTABLECIMIENTO,:ANIMAL,NULL,:OTRO,:HBA,NULL,NULL,:NOMBRE,NULL,:RAZA,:SEXO,NULL,0,:NACIMIENTO,NULL,NULL,'S',:COLOR,0,NULL,NULL,NULL,NULL,NULL,NULL);
                  END

                  IF (:ANIMAL IS NOT NULL) THEN
                  BEGIN
                     UPDATE AUX_IMP_ERA SET ID_ANIMAL = :ANIMAL WHERE (RP = :RP);
                     UPDATE AUX_IMP_ERA SET TIPO_SERVICIO = :TIPO WHERE (RP = :RP);
                  END
              END

  END

  SUSPEND;

END ^

SET TERM ; ^

