SET TERM ^ ;

CREATE OR ALTER PROCEDURE REP_LISTADO_CAB_BRA(
  ESTABLECIMIENTO INTEGER)
RETURNS(
  ID_ANIMAL INTEGER,
  ID_RP VARCHAR(10) CHARACTER SET NONE,
  ID_HBA VARCHAR(10) CHARACTER SET NONE,
  ID_SENASA VARCHAR(9) CHARACTER SET NONE,
  FECHA_NACIMIENTO DATE,
  NOMBRE VARCHAR(100) CHARACTER SET NONE,
  APODO VARCHAR(100) CHARACTER SET NONE,
  RAZA INTEGER,
  CATEGORIA INTEGER,
  SUBCATEGORIA INTEGER,
  PESO DECIMAL(18, 2),
  RODEO INTEGER,
  POTRERO INTEGER,
  CONDICION_CORPORAL INTEGER,
  SEXO INTEGER,
  ESTADO_REPRO VARCHAR(30) CHARACTER SET NONE,
  COLOR INTEGER,
  COLORNOMBRE VARCHAR(50) CHARACTER SET NONE,
  RAZANOMBRE VARCHAR(4) CHARACTER SET NONE,
  CIRCUNFERENCIA_ESCROTAL DOUBLE PRECISION,
  ACTIVO VARCHAR(2) CHARACTER SET NONE,
  RP_PADRE VARCHAR(10) CHARACTER SET NONE,
  NOMBRE_PADRE VARCHAR(100) CHARACTER SET NONE,
  APODO_PADRE VARCHAR(100) CHARACTER SET NONE,
  ORIGEN_PADRE VARCHAR(100) CHARACTER SET NONE,
  RP_MADRE VARCHAR(10) CHARACTER SET NONE,
  NOMBRE_MADRE VARCHAR(100) CHARACTER SET NONE,
  APODO_MADRE VARCHAR(100) CHARACTER SET NONE,
  ORIGEN_MADRE VARCHAR(100) CHARACTER SET NONE,
  NACERDEP DECIMAL(18, 2),
  DESTDEP DECIMAL(18, 2),
  GESTDEP DECIMAL(18, 2),
  LECHEDEP DECIMAL(18, 2),
  FINALDEP DECIMAL(18, 2),
  CEDEP DECIMAL(18, 2),
  NACERPREC DECIMAL(18, 2),
  DESTPREC DECIMAL(18, 2),
  GESTPREC DECIMAL(18, 2),
  LECHEPREC DECIMAL(18, 2),
  FINALPREC DECIMAL(18, 2),
  CEPREC DECIMAL(18, 2),
  ID_IE VARCHAR(64) CHARACTER SET NONE,
  INFORMADO_AFIP VARCHAR(2) CHARACTER SET NONE)
AS
DECLARE VARIABLE ESTADO_REPRODUCTIVO INTEGER;
DECLARE VARIABLE ESTADO_ACTUAL VARCHAR(50);
DECLARE VARIABLE MBI INTEGER;
DECLARE VARIABLE MBE INTEGER;
DECLARE VARIABLE PI INTEGER;
DECLARE VARIABLE PE INTEGER;
DECLARE VARIABLE PESO205 DOUBLE PRECISION;
DECLARE VARIABLE PESO365 DOUBLE PRECISION;
DECLARE VARIABLE PESO550 DOUBLE PRECISION;
DECLARE VARIABLE PESONACER DOUBLE PRECISION;
DECLARE VARIABLE ID_ORIGEN INTEGER;
DECLARE VARIABLE ANIO INTEGER;
DECLARE VARIABLE CANT_PI INTEGER;
DECLARE VARIABLE CANT_PE INTEGER;
BEGIN
  /* Procedure body */
  
  
  FOR SELECT TA.ID_ANIMAL, TA.ID_RP, TA.ID_HBA, TA.ID_SENASA, TA.FECHA_NACIMIENTO, TA.NOMBRE, TA.APODO, TA.RAZA, TA.CATEGORIA,
             TA.SUBCATEGORIA, TA.RODEO, TA.POTRERO, TA.CONDICION_CORPORAL, TA.ESTADO_ACTUAL, TA.ESTADO_REPRODUCTIVO,
             TA.MADRE_BIOLOGICA_INTERNA, TA.MADRE_BIOLOGICA_EXTERNA, TA.PADRE_INTERNO, TA.PADRE_EXTERNO, TA.PESO, TA.PESO205,
             TA.PESO365, TA.PESO550, TA.PESONACER, TA.SEXO, TA.COLOR, TA.CIRCUNFERENCIA_ESCROTAL, TA.ACTIVO, TA.ID_IE, CASE TA.INFORMADO_AFIP WHEN 'S' THEN 'SI' WHEN 'N' THEN 'NO' END
      FROM TAB_ANIMALES TA WHERE TA.ESTABLECIMIENTO = :ESTABLECIMIENTO
      INTO :ID_ANIMAL, :ID_RP, :ID_HBA, :ID_SENASA, :FECHA_NACIMIENTO, :NOMBRE, :APODO, :RAZA, :CATEGORIA, :SUBCATEGORIA, :RODEO,
           :POTRERO, :CONDICION_CORPORAL, :ESTADO_ACTUAL, :ESTADO_REPRODUCTIVO, :MBI, :MBE, :PI, :PE, :PESO, :PESO205, :PESO365,
           :PESO550, :PESONACER, :SEXO, :COLOR, :CIRCUNFERENCIA_ESCROTAL, :ACTIVO, :ID_IE, :INFORMADO_AFIP
  DO
  BEGIN
  
       /* BUSCO DATOS DEL PADRE */
       
       NOMBRE_PADRE = '';
       APODO_PADRE = '';
       RP_PADRE = '';
       ID_ORIGEN = NULL;
       
       SELECT CODIGO FROM COD_RAZAS WHERE ID_RAZA = :RAZA
       INTO :RAZANOMBRE;
       
       SELECT NOMBRE FROM COD_COLORES WHERE ID_COLOR = :COLOR
       INTO :COLORNOMBRE;

       IF (:PI IS NOT NULL) THEN
       BEGIN
            SELECT COUNT(*) FROM TAB_ANIMALES WHERE ESTABLECIMIENTO = :ESTABLECIMIENTO AND ID_ANIMAL = :PI
            INTO :CANT_PI;
            
            IF (:CANT_PI = 1) THEN
            BEGIN
                 SELECT ID_RP, NOMBRE, APODO, ORIGEN_ANIMAL FROM TAB_ANIMALES WHERE ESTABLECIMIENTO = :ESTABLECIMIENTO AND ID_ANIMAL = :PI
                 INTO :RP_PADRE, :NOMBRE_PADRE, :APODO_PADRE, :ID_ORIGEN;
            END
            ELSE
            BEGIN
                 IF (:CANT_PI > 1) THEN
                    RP_PADRE = 'MULTIPLES';
            END
       END
       ELSE
       BEGIN
           SELECT COUNT(*) FROM REL_PADRES_INTERNOS WHERE ESTABLECIMIENTO = :ESTABLECIMIENTO AND ANIMAL = :ID_ANIMAL
           INTO :CANT_PI;
           
           IF (:CANT_PI = 1) THEN
           BEGIN
                SELECT PADRE_INTERNO FROM REL_PADRES_INTERNOS WHERE ESTABLECIMIENTO = :ESTABLECIMIENTO AND ANIMAL = :ID_ANIMAL
                INTO :PI;
           
                IF (:PI IS NOT NULL) THEN
                BEGIN
                     SELECT ID_RP, NOMBRE, APODO, ORIGEN_ANIMAL FROM TAB_ANIMALES WHERE ESTABLECIMIENTO = :ESTABLECIMIENTO AND ID_ANIMAL = :PI
                     INTO :RP_PADRE, :NOMBRE_PADRE, :APODO_PADRE, :ID_ORIGEN;
                END
           END
           ELSE
           BEGIN
                IF (:CANT_PI > 1) THEN
                   RP_PADRE = 'MULTIPLES';
           END
       END

       IF (:ID_ORIGEN IS NOT NULL) THEN
       BEGIN
            SELECT SINONIMO FROM COD_ORIGEN WHERE ID_ORIGEN = :ID_ORIGEN
            INTO :ORIGEN_PADRE;
       END
       
       IF (:PE IS NOT NULL) THEN
       BEGIN
            SELECT COUNT(*) FROM TAB_ANIMALES_EXTERNOS WHERE /*ESTABLECIMIENTO = :ESTABLECIMIENTO AND*/ ID_ANIMAL_EXTERNO = :PE
            INTO :CANT_PE;
            
            IF (:CANT_PE = 1) THEN
            BEGIN
                 SELECT ID_RP, NOMBRE, APODO FROM TAB_ANIMALES_EXTERNOS WHERE /*ESTABLECIMIENTO = :ESTABLECIMIENTO AND*/ ID_ANIMAL_EXTERNO = :PE
                 INTO :RP_PADRE, :NOMBRE_PADRE, :APODO_PADRE;
            END
            ELSE
            BEGIN
                 IF (:CANT_PE = 0) THEN
                 BEGIN
                      SELECT COUNT(*) FROM REL_PADRES_EXTERNOS WHERE ESTABLECIMIENTO = :ESTABLECIMIENTO AND ANIMAL = :ID_ANIMAL
                      INTO :CANT_PE;
                 
                      IF (:CANT_PE = 1) THEN
                      BEGIN
                           SELECT PADRE_EXTERNO FROM REL_PADRES_EXTERNOS WHERE ESTABLECIMIENTO = :ESTABLECIMIENTO AND ANIMAL = :ID_ANIMAL
                           INTO :PE;
            
                           IF (:PE IS NOT NULL) THEN
                           BEGIN
                                SELECT ID_RP, NOMBRE, APODO FROM TAB_ANIMALES_EXTERNOS WHERE /*ESTABLECIMIENTO = :ESTABLECIMIENTO AND*/ ID_ANIMAL_EXTERNO = :PE
                                INTO :RP_PADRE, :NOMBRE_PADRE, :APODO_PADRE;
                           END
                      END
                      ELSE
                      BEGIN
                           IF (:CANT_PE > 0) THEN
                              RP_PADRE = 'MULTIPLES';
                      END
                 END
                 ELSE
                 BEGIN
                      RP_PADRE = 'MULTIPLES';
                 END
            END
       END
       ELSE
       BEGIN
            SELECT COUNT(*) FROM REL_PADRES_EXTERNOS WHERE ESTABLECIMIENTO = :ESTABLECIMIENTO AND ANIMAL = :ID_ANIMAL
              INTO :CANT_PE;

              IF (:CANT_PE = 1) THEN
              BEGIN
                   SELECT PADRE_EXTERNO FROM REL_PADRES_EXTERNOS WHERE ESTABLECIMIENTO = :ESTABLECIMIENTO AND ANIMAL = :ID_ANIMAL
                   INTO :PE;

                   IF (:PE IS NOT NULL) THEN
                   BEGIN
                        SELECT ID_RP, NOMBRE, APODO FROM TAB_ANIMALES_EXTERNOS WHERE /*ESTABLECIMIENTO = :ESTABLECIMIENTO AND*/ ID_ANIMAL_EXTERNO = :PE
                        INTO :RP_PADRE, :NOMBRE_PADRE, :APODO_PADRE;
                   END
              END
              ELSE
              BEGIN
                   IF (:CANT_PE > 0) THEN
                      RP_PADRE = 'MULTIPLES';
              END
       END
       
       
       
       /*  BUSCO DATOS DE LA MADRE  */
       
       RP_MADRE = '';
       NOMBRE_MADRE = '';
       APODO_MADRE = '';
       ORIGEN_MADRE = '';
       ID_ORIGEN = NULL;
       
       IF (:MBI IS NOT NULL) THEN
       BEGIN
            SELECT ID_RP, NOMBRE, APODO, ORIGEN_ANIMAL FROM TAB_ANIMALES WHERE ESTABLECIMIENTO = :ESTABLECIMIENTO AND ID_ANIMAL = :MBI
            INTO :RP_MADRE, :NOMBRE_MADRE, :APODO_MADRE, :ID_ORIGEN;

            IF (:ID_ORIGEN IS NOT NULL) THEN
            BEGIN
                 SELECT SINONIMO FROM COD_ORIGEN WHERE ID_ORIGEN = :ID_ORIGEN
                 INTO :ORIGEN_MADRE;
            END
       END
       
       IF (:MBE IS NOT NULL) THEN
       BEGIN
            SELECT ID_RP, NOMBRE, APODO FROM TAB_ANIMALES_EXTERNOS WHERE /*ESTABLECIMIENTO = :ESTABLECIMIENTO AND*/ ID_ANIMAL_EXTERNO = :MBE
            INTO :RP_MADRE, :NOMBRE_MADRE, :APODO_MADRE;
       END
       
       
       /* BUSCO LOS DEPS */

       SELECT FIRST 1 ANIO FROM TAB_DEP WHERE ANIMAL = :ID_ANIMAL AND ESTABLECIMIENTO = :ESTABLECIMIENTO ORDER BY ANIO ASC
       INTO :ANIO;
       
       SELECT NACERDEP, DESTDEP, GESTDEP, LECHEDEP, FINALDEP, CEDEP, NACERPREC, DESTPREC, GESTPREC, LECHEPREC, FINALPREC, CEPREC
       FROM TAB_DEP WHERE ((ANIO = :ANIO) AND (ANIMAL = :ID_ANIMAL) AND (ESTABLECIMIENTO = :ESTABLECIMIENTO))
       INTO :NACERDEP, :DESTDEP, :GESTDEP, :LECHEDEP, :FINALDEP, :CEDEP, :NACERPREC, :DESTPREC, :GESTPREC, :LECHEPREC, :FINALPREC, :CEPREC;
       

       /* BUSCO ESTADO REPRODUCTIVO */
       
       SELECT MSG_ESTADO FROM COD_ESTADOS_REPRODUCTIVOS WHERE ID_ESTADO_REPRODUCTIVO = :ESTADO_REPRODUCTIVO
       INTO :ESTADO_REPRO;
       

       SUSPEND;
  END
END ^

SET TERM ; ^


