SET TERM ^ ;

CREATE OR ALTER PROCEDURE REP_MOVIMIENTOS_ALIMENTOS(
  DESDE DATE,
  HASTA DATE,
  TIPOALTA INTEGER,
  TIPOBAJA INTEGER,
  NOMBRE VARCHAR(50) CHARACTER SET NONE)
RETURNS(
  TIPO_MOVIMIENTO VARCHAR(50) CHARACTER SET NONE,
  FECHA DATE,
  ALIMENTO VARCHAR(50) CHARACTER SET NONE,
  CANTIDAD FLOAT,
  PRECIO FLOAT)
AS
DECLARE VARIABLE A1 VARCHAR(255);
DECLARE VARIABLE A2 VARCHAR(255);
DECLARE VARIABLE A3 VARCHAR(255);
DECLARE VARIABLE A4 VARCHAR(255);
DECLARE VARIABLE ALIM INTEGER;
DECLARE VARIABLE TIPO_M INTEGER;
BEGIN
     A1 = '';
     A2 = '';
     A3 = '';
     A4 = '';
     
     IF (NOMBRE IS NULL) THEN
        A1 = 'SELECT E.FECHA, E.CANTIDAD, E.COSTO, E.ALIMENTO, E.TIPO_MOVIMIENTO FROM EVE_MOVIMIENTO_ALIMENTACION E WHERE E.ID_EVENTO > 0 ';
     ELSE
        A1 = 'SELECT E.FECHA, E.CANTIDAD, E.COSTO, E.ALIMENTO, E.TIPO_MOVIMIENTO FROM EVE_MOVIMIENTO_ALIMENTACION E JOIN COD_TIPOS_SUPLEMENTACIONES C ON (E.ALIMENTO = C.ID_TIPO_SUPLEMENTACION) WHERE E.ID_EVENTO > 0 ';

     IF (DESDE IS NOT NULL) THEN
        A2 = ' AND E.FECHA BETWEEN '''||CAST(DESDE AS VARCHAR(10))||''' AND '''||CAST(HASTA AS VARCHAR(10))||''' ';
     IF ((TIPOALTA IS NOT NULL) AND (TIPOBAJA IS NULL)) THEN
        A3 = ' AND E.TIPO_MOVIMIENTO = '||TIPOALTA||' ';
     ELSE
     BEGIN
          IF ((TIPOALTA IS NULL) AND (TIPOBAJA IS NOT NULL)) THEN
             A3 = ' AND E.TIPO_MOVIMIENTO = '||TIPOBAJA||' ';
          ELSE
              IF ((TIPOALTA IS NOT NULL) AND (TIPOBAJA IS NOT NULL)) THEN
                 A3 = ' AND ((E.TIPO_MOVIMIENTO = '||TIPOALTA||') OR (E.TIPO_MOVIMIENTO = '||TIPOBAJA||')) ';
     END
     IF (NOMBRE IS NOT NULL) THEN
        A4 = ' AND C.NOMBRE LIKE ''%'||NOMBRE||'%'' ';
        
        
     FOR EXECUTE STATEMENT A1||A2||A3||A4
         INTO :FECHA, :CANTIDAD, :PRECIO, :ALIM, :TIPO_M
     DO
     BEGIN
          SELECT NOMBRE FROM COD_MOVIMIENTO_ALIMENTACION WHERE ID_MOVIMIENTO_ALIMENTACION = :TIPO_M
          INTO :TIPO_MOVIMIENTO;
          SELECT NOMBRE FROM COD_TIPOS_SUPLEMENTACIONES WHERE ID_TIPO_SUPLEMENTACION = :ALIM
          INTO :ALIMENTO;
          
          IF (TIPO_M <> 4) THEN
             PRECIO = PRECIO * CANTIDAD;
          
          SUSPEND;
     END
        
END ^

SET TERM ; ^

