SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_CREACION_GRUPO(
  ESTABLECIMIENTO INTEGER,
  NOMBREGRUPO VARCHAR(50) CHARACTER SET NONE,
  DESCRIPCIONGRUPO VARCHAR(255) CHARACTER SET NONE,
  TIPO VARCHAR(1) CHARACTER SET NONE,
  TIPO_EVENTO INTEGER,
  NRO_DTE INTEGER,
  PATH_DTE VARCHAR(255) CHARACTER SET NONE)
RETURNS(
  IDNUEVOGRUPO INTEGER)
AS
BEGIN
  IDNUEVOGRUPO = GEN_ID(GEN_ID_GRUPOS,1);

  /*INSERTO EL GRUPO*/

  INSERT INTO TAB_GRUPOS (ESTABLECIMIENTO,ID_GRUPO,NOMBRE,DESCRIPCION,TIPO, tipo_evento, NRO_DTE, PATH_DTE)
    VALUES (:ESTABLECIMIENTO, :IDNUEVOGRUPO, :NOMBREGRUPO, :DESCRIPCIONGRUPO,:TIPO, :tipo_evento, :NRO_DTE, :PATH_DTE);
  SUSPEND;

END ^

SET TERM ; ^

