SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_DTE_GRUPO(
  DTE INTEGER,
  PDTE VARCHAR(255) CHARACTER SET NONE,
  ESTABLE INTEGER,
  ID_GRUPO INTEGER)
AS
BEGIN
  UPDATE TAB_GRUPOS SET NRO_DTE = :DTE, PATH_DTE = :PDTE
  WHERE ((TAB_GRUPOS.ESTABLECIMIENTO = :ESTABLE)
         and (TAB_GRUPOS.ID_GRUPO = :ID_GRUPO));

END ^

SET TERM ; ^

