SET TERM ^ ;

CREATE OR ALTER PROCEDURE UNDO_DECLARADO_AFIP(
  ID_EVENTO INTEGER)
AS
DECLARE VARIABLE ID INTEGER;
DECLARE VARIABLE ES INTEGER;
BEGIN
 EXECUTE PROCEDURE GEN_ELIMINAR_DE_GRUPO(:ID_EVENTO);
 
 SELECT ANIMAL, ESTABLECIMIENTO
 FROM EVE_EVENTOS
 WHERE (ID_EVENTO = :ID_EVENTO)
 INTO :ID, :ES;

 UPDATE TAB_ANIMALES
 SET INFORMADO_AFIP = 'N'
 WHERE ID_ANIMAL = :ID
 AND ESTABLECIMIENTO = :ES;
 
 DELETE FROM EVE_EVENTOS WHERE (ID_EVENTO = :ID_EVENTO);
END ^

SET TERM ; ^

