SET TERM ^ ;

CREATE OR ALTER PROCEDURE UNDO_ELIMINAR_EVENTO(
  ID_EVENTO INTEGER)
RETURNS(
  MJE VARCHAR(255) CHARACTER SET NONE)
AS
DECLARE VARIABLE VTIPO INTEGER;
BEGIN
    MJE = '';
    SELECT TIPO FROM EVE_EVENTOS
    WHERE (ID_EVENTO = :ID_EVENTO)
    INTO :VTIPO;
   
    IF (VTIPO = 1) THEN
        EXECUTE PROCEDURE UNDO_ABORTO(:ID_EVENTO);
    IF (VTIPO = 2) THEN
        EXECUTE PROCEDURE UNDO_ALTA_DIRECTA(:ID_EVENTO);
    IF (VTIPO = 3) THEN
        EXECUTE PROCEDURE UNDO_BAJA(:ID_EVENTO);
	IF (VTIPO = 4) THEN
		EXECUTE PROCEDURE UNDO_CALIDAD_SEMINAL(:ID_EVENTO);
	IF (VTIPO = 5) THEN
		EXECUTE PROCEDURE UNDO_CAMBIO_UBICACION(:ID_EVENTO);
	IF (VTIPO = 6) THEN
		EXECUTE PROCEDURE UNDO_CAPACIDAD_DE_SERVICIO(:ID_EVENTO);
	IF (VTIPO = 7) THEN
		EXECUTE PROCEDURE UNDO_CASTRACION(:ID_EVENTO);
	IF (VTIPO = 8) THEN
		EXECUTE PROCEDURE UNDO_CIRCUNFERENCIA_ESCROTAL(:ID_EVENTO);
	IF (VTIPO = 9) THEN
		EXECUTE PROCEDURE UNDO_CONDICION_CORPORAL(:ID_EVENTO);
	IF (VTIPO = 10) THEN
		EXECUTE PROCEDURE UNDO_DESTETE(:ID_EVENTO);
	IF (VTIPO = 11) THEN
		EXECUTE PROCEDURE UNDO_DETECCION_CELO(:ID_EVENTO);
	IF (VTIPO = 12) THEN
		EXECUTE PROCEDURE UNDO_DIAGNOSTICO_ENFERMEDAD(:ID_EVENTO);
	IF (VTIPO = 13) THEN
		EXECUTE PROCEDURE UNDO_DIAGNOSTICO_GESTACION(:ID_EVENTO);
	IF (VTIPO = 14) THEN
		EXECUTE PROCEDURE UNDO_DISTOCIA(:ID_EVENTO);
	IF (VTIPO = 15) THEN
		EXECUTE PROCEDURE UNDO_EGRESO_SERVICIO(:ID_EVENTO);
	IF (VTIPO = 16) THEN
		EXECUTE PROCEDURE UNDO_EGRESO_TORO(:ID_EVENTO);
	IF (VTIPO = 17) THEN
		EXECUTE PROCEDURE UNDO_PRESERVICIO(:ID_EVENTO);
	IF (VTIPO = 18) THEN
		EXECUTE PROCEDURE UNDO_FERTILIDAD_MACHO(:ID_EVENTO);
	IF (VTIPO = 19) THEN
		EXECUTE PROCEDURE UNDO_IDENTIFICACION(:ID_EVENTO);
	IF (VTIPO = 20) THEN
		EXECUTE PROCEDURE UNDO_INGRESO_SERVICIO(:ID_EVENTO);
	IF (VTIPO = 21) THEN
		EXECUTE PROCEDURE UNDO_INGRESO_TORO(:ID_EVENTO);
	IF (VTIPO = 22) THEN
		EXECUTE PROCEDURE UNDO_MEDICION_FRAME(:ID_EVENTO);
	IF (VTIPO = 23) THEN
		EXECUTE PROCEDURE UNDO_NACIMIENTO(:ID_EVENTO);
	IF (VTIPO = 24) THEN
		EXECUTE PROCEDURE UNDO_PARTO(:ID_EVENTO);
	IF (VTIPO = 25) THEN
		EXECUTE PROCEDURE UNDO_PESO(:ID_EVENTO);
	IF (VTIPO = 26) THEN
		EXECUTE PROCEDURE UNDO_SINCRONIZACION_CELO(:ID_EVENTO);
	IF (VTIPO = 27) THEN
		EXECUTE PROCEDURE UNDO_TRATAMIENTO(:ID_EVENTO);
	IF (VTIPO = 28) THEN
		EXECUTE PROCEDURE UNDO_INSEMINACION_ARTIFICIAL(:ID_EVENTO);
	IF (VTIPO = 29) THEN
		EXECUTE PROCEDURE UNDO_SERVICIO_CORRAL(:ID_EVENTO);
	IF (VTIPO = 30) THEN
		EXECUTE PROCEDURE UNDO_SANGRADO_BRUCELOSIS(:ID_EVENTO);
	IF (VTIPO = 31) THEN
		EXECUTE PROCEDURE UNDO_TUBERCULINIZACION(:ID_EVENTO);
	IF (VTIPO = 32) THEN
		EXECUTE PROCEDURE UNDO_RASPADO_TORO (:ID_EVENTO);
	IF (VTIPO = 36) THEN
		EXECUTE PROCEDURE UNDO_IDENTIFICACION(:ID_EVENTO);
	IF (VTIPO = 39) THEN
		EXECUTE PROCEDURE UNDO_PARTO_MASIVO(:ID_EVENTO);
	IF (VTIPO = 41) THEN
		EXECUTE PROCEDURE UNDO_CALIDAD_CARNE(:ID_EVENTO);
	IF (VTIPO = 44) THEN
		EXECUTE PROCEDURE UNDO_ACTIVIDAD(:ID_EVENTO);
	IF (VTIPO = 45) THEN
		EXECUTE PROCEDURE UNDO_SUPLEMENTACION(:ID_EVENTO);
	IF (VTIPO = 47) THEN
		EXECUTE PROCEDURE UNDO_FLUSHING(:ID_EVENTO);
	IF (VTIPO = 48) THEN
		EXECUTE PROCEDURE UNDO_TRANSFERENCIA(:ID_EVENTO);
	IF (VTIPO = 52) THEN
		EXECUTE PROCEDURE UNDO_EXTRACCION_SEMEN(:ID_EVENTO);
	IF (VTIPO = 53) THEN
		EXECUTE PROCEDURE UNDO_CAMBIO_CATEGORIA(:ID_EVENTO);
	IF (VTIPO = 58) THEN
		EXECUTE PROCEDURE UNDO_DECLARADO_AFIP(:ID_EVENTO);	
		
    SUSPEND;

END ^

SET TERM ; ^

