INSERT INTO REL_CATEGORIAS_TIPOS_EVENTO (CATEGORIA, TIPO_EVENTO) VALUES (1, 58);

INSERT INTO REL_CATEGORIAS_TIPOS_EVENTO (CATEGORIA, TIPO_EVENTO) VALUES (2, 58);

INSERT INTO REL_CATEGORIAS_TIPOS_EVENTO (CATEGORIA, TIPO_EVENTO) VALUES (3, 58);

INSERT INTO REL_CATEGORIAS_TIPOS_EVENTO (CATEGORIA, TIPO_EVENTO) VALUES (4, 58);

INSERT INTO REL_CATEGORIAS_TIPOS_EVENTO (CATEGORIA, TIPO_EVENTO) VALUES (5, 58);

INSERT INTO REL_CATEGORIAS_TIPOS_EVENTO (CATEGORIA, TIPO_EVENTO) VALUES (6, 58);



