SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_EVE_INSEMINACION(
  FECHA DATE,
  CANTIDAD INTEGER,
  OBSERVACION VARCHAR(255) CHARACTER SET NONE,
  SEMEN INTEGER,
  PRECIO FLOAT,
  RESPONSABLE INTEGER,
  TIPO INTEGER,
  ANIMAL INTEGER,
  ID_GRUPO INTEGER,
  ESTABLECIMIENTO INTEGER,
  LOG_USUARIO INTEGER,
  SERVICIO INTEGER,
  CONDICION_CORPORAL INTEGER,
  HORA TIME,
  HORA_FIN TIME,
  HORAS_POST_CELO INTEGER,
  LOG_FECHA_MODIFICADO DATE,
  RODEO INTEGER,
  POTRERO INTEGER)
AS
DECLARE VARIABLE TIPOEVE INTEGER;
DECLARE VARIABLE IDNUEVOEVENTO INTEGER;
DECLARE VARIABLE NUEVACANTIDAD INTEGER;
DECLARE VARIABLE R_AUX INTEGER;
DECLARE VARIABLE P_AUX INTEGER;
DECLARE VARIABLE RODEO_AUX INTEGER;
DECLARE VARIABLE POTRERO_AUX INTEGER;
DECLARE VARIABLE CANTIDADEVENTOSPOSTERIORES INTEGER;
BEGIN
    TIPOEVE = 28;
    NUEVACANTIDAD = :CANTIDAD;
    SELECT ID_EVENTO FROM SP_CREACION_EVE_EVENTOS(:FECHA,:ANIMAL, NULL,:OBSERVACION,:TIPOEVE,:ESTABLECIMIENTO,:RESPONSABLE,
    :LOG_USUARIO,:LOG_FECHA_MODIFICADO)
    INTO :IDNUEVOEVENTO;

        /*registro el movimiento */
    EXECUTE PROCEDURE SP_MOVIMIENTO_SEMEN(:SEMEN,:NUEVACANTIDAD,:FECHA,:PRECIO,4, NULL,:OBSERVACION,0,4,NULL,'S','');

   /* ejecuto condicion corporal*/
    if (CONDICION_CORPORAL is Not Null) then
      EXECUTE PROCEDURE SP_CONDICION_CORPORAL(:CONDICION_CORPORAL, :FECHA, :ANIMAL, 'Evento CC disparado por IA', :ESTABLECIMIENTO,
                                              :RESPONSABLE, :LOG_USUARIO, :LOG_FECHA_MODIFICADO, :IDNUEVOEVENTO, NULL);

    SELECT RODEO, POTRERO
     FROM TAB_ANIMALES
     WHERE (ID_ANIMAL = :ANIMAL)
     INTO :RODEO_AUX, :POTRERO_AUX;

     R_AUX = RODEO;
     P_AUX = POTRERO;

     IF ((RODEO_AUX = RODEO) OR (RODEO IS NULL)) THEN
        RODEO = RODEO_AUX;
     IF ((POTRERO_AUX = POTRERO) OR (POTRERO IS NULL)) THEN
        POTRERO = POTRERO_AUX;


  /*agrego el animal en REL_PERTENECE GRUPO*/
    if (ID_GRUPO is Not Null) then
    insert into REL_PERTENECE_GRUPO (GRUPO, ANIMAL, ESTABLECIMIENTO, ACTIVO)
       values   (:ID_GRUPO, :ANIMAL, :ESTABLECIMIENTO, 'S');

   /*Inserta en REL_GRUPOS_EVENTO*/
    EXECUTE PROCEDURE Gen_Agregar_En_Grupo (:ESTABLECIMIENTO ,:IDNUEVOEVENTO ,:ID_GRUPO );

  /*agrego EVENTO EN EVE_INSEMINACION_ARTIFICIAL*/
    insert into EVE_INSEMINACION_ARTIFICIAL (SERVICIO, SEMEN, DOSIS, ID_EVENTO, HORA, HORA_FIN, HORAS_POST_CELO)
                             values   (:SERVICIO, :SEMEN, :CANTIDAD, :IDNUEVOEVENTO, :HORA, :HORA_FIN, :HORAS_POST_CELO);

 /*cambio el estado Reproductivo de la Hembra*/
   SELECT CANTIDAD FROM GEN_CAMBIO_ESTADO_REPRODUCTIVO(:ANIMAL, :FECHA)
   INTO :CANTIDADEVENTOSPOSTERIORES;
   IF (CANTIDADEVENTOSPOSTERIORES = 0) THEN
     UPDATE TAB_ANIMALES SET ESTADO_REPRODUCTIVO = 5, ESTADO_ACTUAL = 'Servida' WHERE (ID_ANIMAL = :ANIMAL);

   UPDATE EVE_INSEMINACION_ARTIFICIAL SET ESTADO_REPRODUCTIVO = 5 WHERE (id_evento = :IDNUEVOEVENTO);

   IF ((R_AUX IS NOT NULL) OR (P_AUX IS NOT NULL)) THEN
         EXECUTE PROCEDURE SP_CAMBIO_UBICACION(:POTRERO, :RODEO, NULL, :FECHA, :ANIMAL, 'Evento Disparado por Inseminación Artificial',
           :ESTABLECIMIENTO, :RESPONSABLE, :LOG_USUARIO, :LOG_FECHA_MODIFICADO, :IDNUEVOEVENTO);

   SUSPEND;
END ^ 

SET TERM ^ ;