SET TERM ^ ;

CREATE OR ALTER PROCEDURE REP_CIERRE_LOTE_DETALLE_ALIM(
  POTRERO INTEGER,
  RODEO INTEGER,
  ESTABLECIMIENTO INTEGER,
  FECHA_INI DATE,
  FECHA_FIN DATE)
RETURNS(
  ID_ANIMAL INTEGER,
  RACION INTEGER,
  DIAS INTEGER,
  COSTO FLOAT,
  GANANCIA FLOAT,
  CONSUMO_TC FLOAT,
  COSTO_KG FLOAT)
AS
DECLARE VARIABLE FECHA_INI_R DATE;
DECLARE VARIABLE FECHA_FIN_R DATE;
DECLARE VARIABLE EVE_ALIM INTEGER;
DECLARE VARIABLE CONSUMO_AUX FLOAT;
DECLARE VARIABLE PRECIO FLOAT;
DECLARE VARIABLE PORC_USADO FLOAT;
DECLARE VARIABLE PORC_MS FLOAT;
DECLARE VARIABLE CONSUMO FLOAT;
DECLARE VARIABLE PESO_INI FLOAT;
DECLARE VARIABLE PESO_FIN FLOAT;
DECLARE VARIABLE PORC_PROM DECIMAL(18, 2);
DECLARE VARIABLE PORC DECIMAL(18, 2);
DECLARE VARIABLE MS DECIMAL(18, 2);
BEGIN

     IF (RODEO IS NULL) THEN
     BEGIN
         FOR SELECT EE.ANIMAL, EE.FECHA, ES.TIPO_SUPLEMENTACION, EE.ID_EVENTO, ES.CANT_RACION FROM EVE_SUPLEMENTACION ES JOIN EVE_EVENTOS EE ON ES.ID_EVENTO = EE.ID_EVENTO
             JOIN TAB_ANIMALES TA ON EE.ANIMAL = TA.ID_ANIMAL WHERE TA.POTRERO = :POTRERO AND TA.ESTABLECIMIENTO = :ESTABLECIMIENTO AND EE.TIPO = 45
             AND EE.FECHA BETWEEN :FECHA_INI AND :FECHA_FIN 
             INTO :ID_ANIMAL, :FECHA_INI_R, :RACION, :EVE_ALIM, :CONSUMO
         DO
         BEGIN
            COSTO = 0;
            PORC_PROM = 0;
            MS = 0;
            PORC = 0;

            FOR SELECT RRS.PORCENTAJE, CTS.PORC_MS FROM REL_RACION_SUPLEMENTO RRS
             JOIN COD_TIPOS_SUPLEMENTACIONES CTS ON RRS.ID_SUPLEMENTO = CTS.ID_TIPO_SUPLEMENTACION WHERE
                   RRS.ID_RACION = :RACION INTO :PORC, :MS
            DO
            BEGIN
                 PORC_PROM = PORC_PROM + (PORC * MS);
            END

            PORC_PROM = PORC_PROM / 100;
            
            FOR SELECT RRS.PRECIO, CTS.PORC_MS, RRS.PORCENTAJE
                FROM REL_RACION_SUPLEMENTO RRS JOIN COD_TIPOS_SUPLEMENTACIONES CTS ON RRS.ID_SUPLEMENTO = CTS.ID_TIPO_SUPLEMENTACION
                WHERE RRS.ID_RACION = :RACION
                INTO :PRECIO, :PORC_MS, :PORC_USADO
            DO
            BEGIN
                 

                 CONSUMO_AUX = (CONSUMO * PORC_USADO) / 100;
                 CONSUMO_TC = (CONSUMO_AUX * 100) / PORC_PROM;
                 COSTO = COSTO + ((CONSUMO_TC * PRECIO) / 1000);
            END
         
           FECHA_FIN_R = NULL;
           SELECT FIRST 1 FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND ID_EVENTO <> :EVE_ALIM AND FECHA BETWEEN :FECHA_INI_R AND :FECHA_FIN
           AND TIPO = 45 ORDER BY FECHA ASC INTO :FECHA_FIN_R;
           IF (FECHA_FIN_R IS NULL) THEN
              SELECT FIRST 1 FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND FECHA BETWEEN :FECHA_INI_R AND :FECHA_FIN
              AND TIPO = 3 ORDER BY FECHA DESC INTO :FECHA_FIN_R;
           IF (FECHA_FIN_R IS NULL) THEN
              FECHA_FIN_R = FECHA_FIN;
           DIAS = FECHA_FIN_R - FECHA_INI_R;
           --COSTO = COSTO * DIAS;
           
           PESO_INI = NULL;
           PESO_FIN = NULL;
           SELECT FIRST 1 EP.PESO FROM EVE_PESO EP JOIN EVE_EVENTOS EE ON EP.ID_EVENTO = EE.ID_EVENTO
           WHERE EE.ANIMAL = :ID_ANIMAL AND EE.FECHA BETWEEN :FECHA_INI_R AND :FECHA_FIN_R AND TIPO = 25
           ORDER BY EE.FECHA ASC INTO :PESO_INI;
           
           SELECT FIRST 1 EP.PESO FROM EVE_PESO EP JOIN EVE_EVENTOS EE ON EP.ID_EVENTO = EE.ID_EVENTO
           WHERE EE.ANIMAL = :ID_ANIMAL AND EE.FECHA BETWEEN :FECHA_INI_R AND :FECHA_FIN_R AND TIPO = 25
           ORDER BY EE.FECHA DESC INTO :PESO_FIN;
           
           IF ((PESO_INI IS NOT NULL) AND (PESO_FIN IS NOT NULL) AND (DIAS > 0)) THEN
           BEGIN
              GANANCIA = (PESO_FIN - PESO_INI) / DIAS;
              IF (GANANCIA > 0) THEN
                -- COSTO_KG = COSTO / (PESO_FIN - PESO_INI);
                   COSTO_KG = COSTO / GANANCIA;
           END
           
           SUSPEND;
         END
     END
     ELSE
     BEGIN
          FOR SELECT EE.ANIMAL, EE.FECHA, ES.TIPO_SUPLEMENTACION, EE.ID_EVENTO, ES.CANT_RACION FROM EVE_SUPLEMENTACION ES JOIN EVE_EVENTOS EE ON ES.ID_EVENTO = EE.ID_EVENTO
             JOIN TAB_ANIMALES TA ON EE.ANIMAL = TA.ID_ANIMAL WHERE TA.RODEO = :RODEO AND TA.ESTABLECIMIENTO = :ESTABLECIMIENTO AND EE.TIPO = 45
             AND EE.FECHA BETWEEN :FECHA_INI AND :FECHA_FIN 
             INTO :ID_ANIMAL, :FECHA_INI_R, :RACION, :EVE_ALIM, :CONSUMO
         DO
         BEGIN
            PORC_PROM = 0;
            MS = 0;
            PORC = 0;
            COSTO = 0;

            FOR SELECT RRS.PORCENTAJE, CTS.PORC_MS FROM REL_RACION_SUPLEMENTO RRS
             JOIN COD_TIPOS_SUPLEMENTACIONES CTS ON RRS.ID_SUPLEMENTO = CTS.ID_TIPO_SUPLEMENTACION WHERE
                   RRS.ID_RACION = :RACION INTO :PORC, :MS
            DO
            BEGIN
                 PORC_PROM = PORC_PROM + (PORC * MS);
            END

            PORC_PROM = PORC_PROM / 100;
            
            FOR SELECT RRS.PRECIO, CTS.PORC_MS, RRS.PORCENTAJE
                FROM REL_RACION_SUPLEMENTO RRS JOIN COD_TIPOS_SUPLEMENTACIONES CTS ON RRS.ID_SUPLEMENTO = CTS.ID_TIPO_SUPLEMENTACION
                WHERE RRS.ID_RACION = :RACION
                INTO :PRECIO, :PORC_MS, :PORC_USADO
            DO
            BEGIN
                 
                 CONSUMO_AUX = (CONSUMO * PORC_USADO) / 100;
                 CONSUMO_TC = (CONSUMO_AUX * 100) / PORC_PROM;
                 COSTO = COSTO + ((CONSUMO_TC * PRECIO) / 1000);
            END

           FECHA_FIN_R = NULL;
           SELECT FIRST 1 FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND ID_EVENTO <> :EVE_ALIM AND FECHA BETWEEN :FECHA_INI_R AND :FECHA_FIN
           AND TIPO = 45 ORDER BY FECHA ASC INTO :FECHA_FIN_R;
           IF (FECHA_FIN_R IS NULL) THEN
              SELECT FIRST 1 FECHA FROM EVE_EVENTOS WHERE ANIMAL = :ID_ANIMAL AND FECHA BETWEEN :FECHA_INI_R AND :FECHA_FIN
              AND TIPO = 3 ORDER BY FECHA DESC INTO :FECHA_FIN_R;
           IF (FECHA_FIN_R IS NULL) THEN
              FECHA_FIN_R = FECHA_FIN;
           DIAS = FECHA_FIN_R - FECHA_INI_R;
          -- COSTO = COSTO * DIAS;

           PESO_INI = NULL;
           PESO_FIN = NULL;
           SELECT FIRST 1 EP.PESO FROM EVE_PESO EP JOIN EVE_EVENTOS EE ON EP.ID_EVENTO = EE.ID_EVENTO
           WHERE EE.ANIMAL = :ID_ANIMAL AND EE.FECHA BETWEEN :FECHA_INI_R AND :FECHA_FIN_R AND TIPO = 25
           ORDER BY EE.FECHA ASC INTO :PESO_INI;

           SELECT FIRST 1 EP.PESO FROM EVE_PESO EP JOIN EVE_EVENTOS EE ON EP.ID_EVENTO = EE.ID_EVENTO
           WHERE EE.ANIMAL = :ID_ANIMAL AND EE.FECHA BETWEEN :FECHA_INI_R AND :FECHA_FIN_R AND TIPO = 25
           ORDER BY EE.FECHA DESC INTO :PESO_FIN;

           IF ((PESO_INI IS NOT NULL) AND (PESO_FIN IS NOT NULL) AND (DIAS > 0)) THEN
           BEGIN
              GANANCIA = (PESO_FIN - PESO_INI) / DIAS;
              IF (GANANCIA > 0) THEN
                 --COSTO_KG = COSTO / (PESO_FIN - PESO_INI);
                 COSTO_KG = COSTO / GANANCIA;
           END

           SUSPEND;
         END
     END
END ^ 

SET TERM ; ^

