SET TERM ^ ;

CREATE OR ALTER PROCEDURE REP_COSTOS_VETERINARIOS(
  ESTABLECIMIENTO INTEGER,
  DESDE DATE,
  HASTA DATE)
RETURNS(
  FECHA DATE,
  ID_GRUPO INTEGER,
  GRUPO VARCHAR(50) CHARACTER SET NONE,
  ID_TIPO_EVENTO INTEGER,
  EVENTO VARCHAR(50) CHARACTER SET NONE,
  TIPO_DESCRIPCION VARCHAR(101) CHARACTER SET NONE,
  ID_RODEO INTEGER,
  RODEO VARCHAR(50) CHARACTER SET NONE,
  POTRERO INTEGER,
  ID_CATEGORIA INTEGER,
  CATEGORIA VARCHAR(20) CHARACTER SET NONE,
  RESPONSABLE VARCHAR(80) CHARACTER SET NONE,
  CANT_ANIMALES INTEGER,
  COSTO DECIMAL(18, 3),
  COSTO_TOTAL DECIMAL(18, 3),
  COSTO_KG DECIMAL(18, 3),
  ACTIVIDAD VARCHAR(20) CHARACTER SET NONE,
  OBSERVACIONES VARCHAR(255) CHARACTER SET NONE)
AS
DECLARE VARIABLE ID_EVENTO INTEGER;
DECLARE VARIABLE CODIGO VARCHAR(2);
DECLARE VARIABLE ID_RESP INTEGER;
DECLARE VARIABLE AUX INTEGER;
DECLARE VARIABLE AUX1 INTEGER;
DECLARE VARIABLE V1 VARCHAR(50);
DECLARE VARIABLE V2 VARCHAR(50);
DECLARE VARIABLE ANIMAL INTEGER;
DECLARE VARIABLE AUXRP VARCHAR(20);
BEGIN
     --RECORRER PRIMERO LOS GRUPOS
     FOR SELECT COUNT(*), EE.RODEO, EE.CATEGORIA, EE.RESPONSABLE, EE.FECHA ,TG.ID_GRUPO, TG.NOMBRE, CTE.NOMBRE, CTE.CODIGO FROM TAB_GRUPOS TG JOIN COD_TIPOS_EVENTO CTE ON TG.TIPO_EVENTO=CTE.ID_TIPO_EVENTO
         JOIN REL_GRUPOS_EVENTO RGE ON RGE.GRUPO = TG.ID_GRUPO JOIN EVE_EVENTOS EE ON RGE.EVENTO = EE.ID_EVENTO
         WHERE ((CTE.CATEGORIA = 8) OR (CTE.CATEGORIA = 6 AND CTE.CODIGO = 'DG') OR (CTE.CATEGORIA = 1 AND CTE.CODIGO = 'FM')) AND
         TG.ESTABLECIMIENTO = :ESTABLECIMIENTO AND TG.TIPO = 'S' AND EE.FECHA BETWEEN :DESDE AND :HASTA
         GROUP BY EE.RODEO, EE.CATEGORIA, EE.RESPONSABLE, EE.FECHA, TG.ID_GRUPO, TG.NOMBRE, CTE.NOMBRE, CTE.CODIGO
         INTO :CANT_ANIMALES, :ID_RODEO, :ID_CATEGORIA, :ID_RESP, :FECHA, :ID_GRUPO, :GRUPO, :EVENTO, :CODIGO
     DO
     BEGIN
          ID_EVENTO = NULL;
          RESPONSABLE = NULL;
          RODEO = NULL;
          CATEGORIA = NULL;
        

          SELECT FIRST 1 EE.ID_EVENTO FROM EVE_EVENTOS EE JOIN REL_GRUPOS_EVENTO RGE ON EE.ID_EVENTO = RGE.EVENTO
          WHERE RGE.GRUPO = :ID_GRUPO INTO :ID_EVENTO;
          
          IF (ID_EVENTO IS NOT NULL) THEN
          BEGIN
               SELECT EE.POTRERO FROM EVE_EVENTOS EE WHERE ID_EVENTO =: ID_EVENTO
                INTO :POTRERO;

               TIPO_DESCRIPCION = NULL;

               SELECT NOMBRE||' '||APELLIDO FROM TAB_EMPLEADOS WHERE ID_EMPLEADO = :ID_RESP AND ESTABLECIMIENTO = :ESTABLECIMIENTO INTO :RESPONSABLE;
               SELECT CODIGO FROM COD_CATEGORIAS WHERE ID_CATEGORIA = :ID_CATEGORIA INTO :CATEGORIA;
               SELECT NOMBRE FROM TAB_RODEOS WHERE ID_RODEO = :ID_RODEO AND ESTABLECIMIENTO = :ESTABLECIMIENTO INTO :RODEO;
              
               IF (CODIGO = 'DG') THEN --DIAGNOSTICO GESTACION
               BEGIN
                  SELECT PRECIO, METODO_DIAGNOSTICO FROM EVE_DIAGNOSTICO_GESTACION WHERE ID_EVENTO = :ID_EVENTO INTO :COSTO, :AUX;
                  SELECT NOMBRE FROM COD_METODOS_DIAGNOSTICO_GESTACI WHERE ID_METODO_DIAGNOSTICO = :AUX INTO TIPO_DESCRIPCION;
               END

               IF (CODIGO = 'FM') THEN --FERTILIDAD MACHO
               BEGIN
                  SELECT PRECIO, METODO_EXAMEN FROM EVE_FERTILIDAD_MACHO WHERE ID_EVENTO = :ID_EVENTO INTO :COSTO, :AUX;
                  SELECT NOMBRE FROM COD_METODOS_EXAMEN_SANITARIO WHERE ID_METODO_EXAMEN = :AUX INTO :TIPO_DESCRIPCION;
               END

               IF (CODIGO = 'SB' OR CODIGO = 'CB') THEN --SANGRADO BRUCELOSIS
                  SELECT PRECIO_TOMA+PRECIO_LAB FROM EVE_SANGRADO_BRUCELOSIS WHERE ID_EVENTO = :ID_EVENTO INTO :COSTO;

               IF (CODIGO = 'TU' OR CODIGO = 'CT') THEN --TUBERCULINIZACION
                  SELECT PRECIO FROM EVE_TUBERCULINIZACION WHERE ID_EVENTO = :ID_EVENTO INTO :COSTO;

               IF (CODIGO = 'RT' OR CODIGO = 'CM') THEN --RASPADO TOROS
                  SELECT PRECIO_TOMA+PRECIO_LAB FROM EVE_RASPADO_TORO WHERE ID_EVENTO = :ID_EVENTO INTO :COSTO;

               IF (CODIGO = 'DE') THEN --DIAGNOSTICO ENFERMEDAD
               BEGIN
                  SELECT PRECIO, ENFERMEDAD FROM EVE_DIAGNOSTICO_ENFERMEDAD WHERE ID_EVENTO = :ID_EVENTO INTO :COSTO, :AUX;
                  SELECT NOMBRE FROM COD_ENFERMEDADES WHERE ID_ENFERMEDAD = :AUX INTO :TIPO_DESCRIPCION;
               END
                  
               IF (CODIGO = 'TR') THEN --TRATAMIENTO
               BEGIN
                  SELECT PRECIO FROM TAB_DATOS_TRATAMIENTO WHERE ID_GRUPO = :ID_GRUPO AND ESTABLECIMIENTO = :ESTABLECIMIENTO INTO :COSTO;
                  SELECT ID_TRATAMIENTO, TIPO FROM EVE_TRATAMIENTO WHERE ID_EVENTO = :ID_EVENTO INTO :AUX, :AUX1;
                  SELECT NOMBRE FROM COD_TIPOS_TRATAMIENTO WHERE ID_TIPO_TRATAMIENTO = :AUX1 INTO :V1;
                  SELECT NOMBRE FROM COD_TRATAMIENTO WHERE ID_TRATAMIENTO = :AUX INTO :V2;
                  TIPO_DESCRIPCION = V1||'-'||V2;
               END
               
               COSTO_TOTAL = COSTO*CAST(CANT_ANIMALES AS FLOAT);
               SUSPEND;

          END
     END
     --RECORRER LOS EVENTOS INDIVIDUALES
     COSTO = NULL;
     COSTO_TOTAL = NULL;
     CANT_ANIMALES = 1;
     GRUPO = NULL;
     ID_GRUPO = NULL;
     
     FOR SELECT EE.ID_EVENTO, EE.RODEO, EE.CATEGORIA, EE.RESPONSABLE, EE.FECHA, CTE.NOMBRE, CTE.CODIGO, EE.ANIMAL FROM EVE_EVENTOS EE JOIN
         COD_TIPOS_EVENTO CTE ON CTE.ID_TIPO_EVENTO = EE.TIPO
         WHERE ((CTE.CATEGORIA = 8) OR (CTE.CATEGORIA = 6 AND CTE.CODIGO = 'DG') OR (CTE.CATEGORIA = 1 AND CTE.CODIGO = 'FM')) AND
         EE.ESTABLECIMIENTO = :ESTABLECIMIENTO AND EE.FECHA BETWEEN :DESDE AND :HASTA
         AND EE.ID_EVENTO NOT IN(SELECT EVENTO FROM REL_GRUPOS_EVENTO WHERE ESTABLECIMIENTO = :ESTABLECIMIENTO)
         INTO :ID_EVENTO, :ID_RODEO, :ID_CATEGORIA, :ID_RESP, :FECHA, :EVENTO, :CODIGO, :ANIMAL
     DO
     BEGIN
          RESPONSABLE = NULL;
          RODEO = NULL;
          CATEGORIA = NULL;

          TIPO_DESCRIPCION = NULL;

          SELECT ID_RP FROM TAB_ANIMALES WHERE ID_ANIMAL = :ANIMAL INTO :AUXRP;
          GRUPO = 'Evento Individual - RP: '||AUXRP;
          SELECT NOMBRE||' '||APELLIDO FROM TAB_EMPLEADOS WHERE ID_EMPLEADO = :ID_RESP AND ESTABLECIMIENTO = :ESTABLECIMIENTO INTO :RESPONSABLE;
          SELECT CODIGO FROM COD_CATEGORIAS WHERE ID_CATEGORIA = :ID_CATEGORIA INTO :CATEGORIA;
          SELECT NOMBRE FROM TAB_RODEOS WHERE ID_RODEO = :ID_RODEO AND ESTABLECIMIENTO = :ESTABLECIMIENTO INTO :RODEO;
          
          IF (CODIGO = 'DG') THEN --DIAGNOSTICO GESTACION
          BEGIN
               SELECT PRECIO, METODO_DIAGNOSTICO FROM EVE_DIAGNOSTICO_GESTACION WHERE ID_EVENTO = :ID_EVENTO INTO :COSTO, :AUX;
               SELECT NOMBRE FROM COD_METODOS_DIAGNOSTICO_GESTACI WHERE ID_METODO_DIAGNOSTICO = :AUX INTO TIPO_DESCRIPCION;
          END

          IF (CODIGO = 'FM') THEN --FERTILIDAD MACHO
          BEGIN
               SELECT PRECIO, METODO_EXAMEN FROM EVE_FERTILIDAD_MACHO WHERE ID_EVENTO = :ID_EVENTO INTO :COSTO, :AUX;
               SELECT NOMBRE FROM COD_METODOS_EXAMEN_SANITARIO WHERE ID_METODO_EXAMEN = :AUX INTO :TIPO_DESCRIPCION;
          END

          IF (CODIGO = 'SB' OR CODIGO = 'CB') THEN --SANGRADO BRUCELOSIS
             SELECT PRECIO_TOMA+PRECIO_LAB FROM EVE_SANGRADO_BRUCELOSIS WHERE ID_EVENTO = :ID_EVENTO INTO :COSTO;

          IF (CODIGO = 'TU' OR CODIGO = 'CT') THEN --TUBERCULINIZACION
             SELECT PRECIO FROM EVE_TUBERCULINIZACION WHERE ID_EVENTO = :ID_EVENTO INTO :COSTO;

          IF (CODIGO = 'RT' OR CODIGO = 'CM') THEN --RASPADO TOROS
             SELECT PRECIO_TOMA+PRECIO_LAB FROM EVE_RASPADO_TORO WHERE ID_EVENTO = :ID_EVENTO INTO :COSTO;

          IF (CODIGO = 'DE') THEN --DIAGNOSTICO ENFERMEDAD
          BEGIN
               SELECT PRECIO, ENFERMEDAD FROM EVE_DIAGNOSTICO_ENFERMEDAD WHERE ID_EVENTO = :ID_EVENTO INTO :COSTO, :AUX;
               SELECT NOMBRE FROM COD_ENFERMEDADES WHERE ID_ENFERMEDAD = :AUX INTO :TIPO_DESCRIPCION;
          END

          IF (CODIGO = 'TR') THEN --TRATAMIENTO
          BEGIN
               SELECT PRECIO FROM TAB_DATOS_TRATAMIENTO WHERE ID_ANIMAL = :ANIMAL AND ESTABLECIMIENTO = :ESTABLECIMIENTO AND EVENTO = :ID_EVENTO INTO :COSTO;
               SELECT ID_TRATAMIENTO, TIPO FROM EVE_TRATAMIENTO WHERE ID_EVENTO = :ID_EVENTO INTO :AUX, :AUX1;
               SELECT NOMBRE FROM COD_TIPOS_TRATAMIENTO WHERE ID_TIPO_TRATAMIENTO = :AUX1 INTO :V1;
               SELECT NOMBRE FROM COD_TRATAMIENTO WHERE ID_TRATAMIENTO = :AUX INTO :V2;
               TIPO_DESCRIPCION = V1||'-'||V2;
          END
             
          COSTO_TOTAL = COSTO;
             
          SUSPEND;
     END
END ^ 

SET TERM ; ^

