CREATE PROCEDURE RN_FECHA_EVENTO(
  ANIMAL INTEGER,
  FECHA DATE,
  TIPO_EVENTO INTEGER)
RETURNS(
  RESULT VARCHAR(1) CHARACTER SET NONE,
  MENSAJE VARCHAR(150) CHARACTER SET NONE)
AS
DECLARE VARIABLE FECHA_ALTA DATE;
DECLARE VARIABLE ERROR INTEGER;
DECLARE VARIABLE TIPO INTEGER;
DECLARE VARIABLE ACTUAL DATE;
DECLARE VARIABLE FECHA_BAJA DATE;
DECLARE VARIABLE FECHA_CAMBIO_UBICACION DATE;
DECLARE VARIABLE TIPO_BAJA INTEGER;
BEGIN
  ERROR = 0;
  -- BUSCO LA FECHA DEL ALTA QUE PUEDE SER POR ALTA DIRECTA O NACIMIENTO
  SELECT FIRST 1 EE.FECHA, EE.TIPO
  FROM EVE_EVENTOS EE WHERE (EE.ANIMAL = :ANIMAL) AND ((EE.TIPO = 2) OR (EE.TIPO = 23))
  ORDER BY FECHA DESC
  INTO FECHA_ALTA, :TIPO;
  IF ((FECHA_ALTA IS NOT NULL) AND(FECHA_ALTA > FECHA)) THEN
  BEGIN
       ERROR = 1;
       RESULT = 'E';
       MENSAJE = 'NO SE PUEDE REGISTRAR EL EVENTO, POR SER ANTERIOR A LA FECHA DE ALTA DEL ANIMAL';
       SUSPEND;
  END

  ACTUAL = CAST('TODAY' AS DATE);
  IF (FECHA > ACTUAL) THEN
  BEGIN
       ERROR = 1;
       RESULT = 'E';
       MENSAJE = 'NO SE PUEDE REGISTRAR EL EVENTO POR SER MAYOR A LA FECHA ACTUAL '||EXTRACT(DAY FROM ACTUAL)||'/'||EXTRACT(MONTH FROM ACTUAL)||'/'||EXTRACT(YEAR FROM ACTUAL);
       SUSPEND;
  END

  FECHA_BAJA = NULL;
  TIPO_BAJA = NULL;
  FECHA_CAMBIO_UBICACION = NULL;
  
  SELECT MAX(FECHA) FROM EVE_EVENTOS WHERE ANIMAL = :ANIMAL AND TIPO = 3 AND FECHA > :FECHA_ALTA
  INTO :FECHA_BAJA;
  IF (FECHA_BAJA IS NOT NULL) THEN
  BEGIN
    -- Obtengo el tipo de baja
    SELECT EVE_BAJA.TIPO
   FROM EVE_BAJA
   INNER JOIN EVE_EVENTOS ON (EVE_BAJA.ID_EVENTO = EVE_EVENTOS.ID_EVENTO AND EVE_EVENTOS.ANIMAL = :ANIMAL)
   WHERE EVE_EVENTOS.FECHA = :FECHA_BAJA
   INTO :TIPO_BAJA;
   
    -- Obtengo si hay cambio de ubicacion
    SELECT MAX(FECHA)
   FROM EVE_EVENTOS
   WHERE EVE_EVENTOS.ANIMAL = :ANIMAL AND TIPO = 5 AND FECHA = :FECHA_BAJA
   INTO :FECHA_CAMBIO_UBICACION;
 
  
       -- Si no es una baja de cecsion emite error, o no tiene cambio de ubicacion en ese mismo dia  
    IF (NOT ((TIPO_BAJA = 2) AND (FECHA_CAMBIO_UBICACION IS NOT NULL))) THEN
    BEGIN
  ERROR = 1;
  RESULT = 'E';
  MENSAJE = 'NO SE PUEDE REGISTRAR EL EVENTO POR SER MAYOR A LA FECHA DE BAJA DEL ANIMAL';
  SUSPEND;
    END

  END

  IF (ERROR = 0) THEN
  BEGIN
       RESULT = 'A';
       MENSAJE = '';
       SUSPEND;
  END
END;